"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "fr" | "en" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  fr: {
    // Header
    "header.features": "Fonctionnalités",
    "header.duel": "Mode Duel",
    "header.pricing": "Tarifs",
    "header.contact": "Contact",
    "header.try_free": "Essayez gratuitement",

    // GMI Page
    "gmi.title": "Intelligence Marché Global",
    "gmi.subtitle": "Découvrez votre réputation dans le monde",
    "gmi.description":
      "Analysez votre présence digitale dans jusqu'à 5 pays simultanément et découvrez où vous avez la meilleure réputation",
    "gmi.search_title": "Recherche à analyser",
    "gmi.search_description": "Entrez le nom de la marque, personne ou entité à analyser",
    "gmi.search_label": "Terme de recherche",
    "gmi.search_placeholder": "Ex: Tesla, Elon Musk, Paris...",
    "gmi.country_selection": "Sélection des pays",
    "gmi.country_description": "Choisissez jusqu'à 5 pays pour votre analyse",
    "gmi.selected_countries": "Pays sélectionnés :",
    "gmi.analyze_button": "Analyser la réputation mondiale",
    "gmi.analyzing": "Analyse en cours...",
    "gmi.estimated_cost": "Coût estimé : {count} requêtes Google",
    "gmi.geo_analysis_title": "Analyse Géolocalisée",
    "gmi.geo_analysis_desc":
      "Obtenez des résultats spécifiques à chaque pays grâce à la géolocalisation des recherches Google",
    "gmi.targeted_analysis_title": "Analyse Ciblée",
    "gmi.targeted_analysis_desc":
      "Maximum 5 pays par analyse avec des résultats précis et détaillés pour chaque région",
    "gmi.detailed_comparison_title": "Comparaison Détaillée",
    "gmi.detailed_comparison_desc":
      "Scores de réputation détaillés avec analyse comparative pour identifier vos meilleurs marchés",

    // Countries
    "country.france": "France",
    "country.germany": "Allemagne",
    "country.spain": "Espagne",
    "country.italy": "Italie",
    "country.uk": "Royaume-Uni",
    "country.uae": "Émirats Arabes Unis",
    "country.saudi": "Arabie Saoudite",
    "country.japan": "Japon",
    "country.china": "Chine",
    "country.usa": "États-Unis",
    "country.canada": "Canada",
    "country.argentina": "Argentine",
    "country.brazil": "Brésil",
    "country.south_africa": "Afrique du Sud",
    "country.congo": "R.D. Congo",
    "country.india": "Inde",
    "country.australia": "Australie",

    // Hero Section
    "hero.badge": "Analyse SEO Instantanée Powered by AI",
    "hero.title_measure": "Mesurez",
    "hero.title_reputation": "votre image en ligne",
    "hero.title_time": "en une minute",
    "hero.subtitle": "3 scores, un résultat clair",
    "hero.title": "Mesurez votre image en ligne en une minute - 3 scores, un résultat clair",
    "hero.subtitle_desc":
      "Découvrez en un instant comment Google et l'IA perçoivent votre nom ou votre marque : visibilité, tonalité et cohérence.",
    "hero.name_label": "Nom / Brand",
    "hero.name_placeholder": "Mon identité, mon entreprise, ma marque...",
    "hero.message_label": "Message",
    "hero.message_placeholder": "Vérifiez si cette phrase matche avec votre identité en ligne",
    "hero.language_label": "Langue d'analyse",
    "hero.language_placeholder": "Sélectionnez une langue",
    "hero.analyze_button": "Analyser maintenant",
    "hero.result_time": "Résultat en 60 secondes",
    "hero.secure": "Gratuit et sécurisé",
    "hero.instant_analysis": "Analyse Instantanée",
    "hero.detailed_results": "Résultats détaillés en 60 secondes",

    // Features Section
    "features.title": "3 scores pour comprendre votre impact",
    "features.subtitle": "Une analyse complète de votre présence digitale en quelques secondes",
    "features.presence_title": "Score de présence",
    "features.presence_subtitle": "SEO + visibilité GPT",
    "features.presence_desc": "Voyez si vous existez là où vos clients et les IA vous cherchent.",
    "features.tone_title": "Score de tonalité",
    "features.tone_subtitle": "positif/négatif",
    "features.tone_desc": "Comprenez l'émotion dominante véhiculée par vos contenus.",
    "features.coherence_title": "Score de cohérence narrative",
    "features.coherence_subtitle": "uniformité du message",
    "features.coherence_desc": "Mesure la plausibilité et l'uniformité de votre message.",

    // Use Cases
    "usecases.title": "Pour qui ?",
    "usecases.subtitle": "Un outil adapté pour tout le monde",
    "usecases.companies": "Entreprises",
    "usecases.companies_desc": "Surveillez vos concurrents et protégez votre réputation contre les attaques.",
    "usecases.media": "Médias",
    "usecases.media_desc": "Cadrez le ton éditorial et détectez les campagnes adverses.",
    "usecases.individuals": "Particuliers",
    "usecases.individuals_desc": "Défendez votre image personnelle contre la désinformation.",
    "usecases.agencies": "Agences de communication",
    "usecases.agencies_desc": "Intelligence concurrentielle et guerre informationnelle pour vos clients.",

    // Example Section
    "example.title": "Exemple de résultat",
    "example.subtitle": "Voici à quoi ressemblent vos scores une fois l'analyse terminée",
    "example.presence": "Présence",
    "example.tone": "Tonalité",
    "example.coherence": "Cohérence",
    "example.scale": "Échelle :",
    "example.how_calculated": "Voir comment c'est calculé",
    "example.simple_mode": "Mode Simple",
    "example.duel_mode": "Mode Duel",
    "example.company_name": "TechCorp Solutions",
    "example.analysis_date": "Analysé le 15 janvier 2025",
    "example.global_score": "Score Global",
    "example.key_metrics": "Métriques Clés",
    "example.search_volume": "Volume de recherche mensuel",
    "example.brand_mentions": "Mentions de marque",
    "example.sentiment_evolution": "Évolution sentiment (30j)",
    "example.strategic_recommendations": "Recommandations Stratégiques",
    "example.rec1_title": "Optimiser le contenu SEO",
    "example.rec1_desc": "Créer 15 articles ciblés sur vos mots-clés principaux",
    "example.rec1_impact": "Impact estimé: +25% visibilité",
    "example.rec2_title": "Renforcer la présence sociale",
    "example.rec2_desc": "Augmenter la fréquence de publication LinkedIn",
    "example.rec2_impact": "Impact estimé: +18% engagement",
    "example.threat_analysis": "Analyse des Menaces",
    "example.threat1": "Concurrent direct avec meilleur SEO",
    "example.threat2": "Mentions négatives sur forums spécialisés",
    "example.threat3": "Absence sur certains canaux clés",
    "example.duel_title": "Nike vs Adidas - Analyse Comparative",
    "example.market_context": "Contexte Marché",
    "example.market_desc": "Secteur sportswear premium, concurrence intense sur l'innovation et l'image de marque",
    "example.category_analysis": "Analyse par Catégorie",
    "example.seo_performance": "Performance SEO",
    "example.social_presence": "Présence Sociale",
    "example.brand_perception": "Perception Marque",
    "example.content_quality": "Qualité Contenu",
    "example.competitive_intelligence": "Intelligence Concurrentielle",
    "example.nike_strengths": "Forces Nike",
    "example.nike_strength1": "Innovation produit constante",
    "example.nike_strength2": "Partenariats athlètes premium",
    "example.nike_strength3": "Storytelling émotionnel fort",
    "example.adidas_strengths": "Forces Adidas",
    "example.adidas_strength1": "Héritage sportif authentique",
    "example.adidas_strength2": "Collaborations mode/streetwear",
    "example.adidas_strength3": "Engagement développement durable",
    "example.nike_weaknesses": "Faiblesses Nike",
    "example.nike_weakness1": "Controverses éthiques récurrentes",
    "example.nike_weakness2": "Prix premium limitant l'accessibilité",
    "example.adidas_weaknesses": "Faiblesses Adidas",
    "example.adidas_weakness1": "Innovation perçue comme moins disruptive",
    "example.adidas_weakness2": "Présence digitale moins agressive",

    // Pricing
    "pricing.title": "Tarifs simples et transparents",
    "pricing.subtitle": "Commencez gratuitement, évoluez selon vos besoins",
    "pricing.free_title": "Gratuit",
    "pricing.free_price": "0€",
    "pricing.free_period": "/mois",
    "pricing.free_feature1": "1 analyse par jour",
    "pricing.free_feature2": "Scores de base",
    "pricing.free_feature3": "Historique 7 jours",
    "pricing.free_feature4": "Support communautaire",
    "pricing.free_cta": "Commencer",
    "pricing.pro_title": "Pro",
    "pricing.pro_price": "899€",
    "pricing.pro_period": "/mois",
    "pricing.pro_feature1": "15 analyses par jour",
    "pricing.pro_feature2": "Scores détaillés + insights",
    "pricing.pro_feature3": "Historique illimité",
    "pricing.pro_feature4": "Rapports PDF",
    "pricing.pro_feature5": "Support prioritaire",
    "pricing.pro_feature6": "API access",
    "pricing.pro_cta": "Contacter les ventes",
    "pricing.ultimate_title": "Ultimate",
    "pricing.ultimate_price": "Sur devis",
    "pricing.ultimate_feature1": "Analyses illimitées",
    "pricing.ultimate_feature2": "Scores avancés + IA personnalisée",
    "pricing.ultimate_feature3": "Intégration API complète",
    "pricing.ultimate_feature4": "Rapports personnalisés",
    "pricing.ultimate_feature5": "Support dédié 24/7",
    "pricing.ultimate_feature6": "Formation équipe",
    "pricing.ultimate_feature7": "SLA garanti",
    "pricing.ultimate_cta": "Demander le prix",
    "pricing.popular": "Populaire",

    // Contact
    "contact.title": "Contactez-nous",
    "contact.subtitle":
      "Votre score ne vous satisfait pas ? Vous voulez influer dessus ? Nous avons les solutions qu'il vous faut.",
    "contact.form_title": "Envoyez-nous un message",
    "contact.email": "Email",
    "contact.email_placeholder": "votre@email.com",
    "contact.message": "Message",
    "contact.message_placeholder": "Décrivez votre besoin ou votre question...",
    "contact.send": "Envoyer le message",
    "contact.success_title": "Message envoyé !",
    "contact.success_desc": "Nous vous répondrons dans les plus brefs délais.",
    "contact.direct_email": "Ou écrivez-nous directement à",
    "contact.email_required": "L'email est requis",
    "contact.email_invalid": "Format d'email invalide",
    "contact.message_required": "Le message est requis",

    // CTA Section
    "cta.title": "Découvrez votre score en 1 minute",
    "cta.subtitle": "Essayez gratuitement notre analyseur et obtenez vos 3 scores instantanément",
    "cta.button": "Essayer maintenant",

    // Footer
    "footer.description": "L'outil d'analyse de présence digitale qui mesure votre impact en 3 scores.",
    "footer.quick_links": "Liens rapides",
    "footer.features": "Fonctionnalités",
    "footer.pricing": "Tarifs",
    "footer.contact": "Contact",
    "footer.legal": "Légal",
    "footer.legal_mentions": "Mentions légales",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "CGU",
    "footer.contact_title": "Contact",
    "footer.support": "Support disponible 7j/7",
    "footer.copyright": "© 2025 Quintilian App. Tous droits réservés.",

    // Legal pages
    "legal.back_home": "Retour à l'accueil",
    "legal.mentions_title": "Mentions légales",
    "legal.privacy_title": "Politique de confidentialité",
    "legal.terms_title": "Conditions générales d'utilisation",

    // Mentions légales
    "legal.editor_info": "Informations sur l'éditeur",
    "legal.company_address": "Adresse : France",
    "legal.hosting_info": "Informations sur l'hébergement",
    "legal.hosting_details":
      "Ce site est hébergé par Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, États-Unis.",
    "legal.intellectual_property": "Propriété intellectuelle",
    "legal.ip_content":
      "L'ensemble des contenus présents sur ce site (textes, images, logos, etc.) sont protégés par le droit d'auteur et appartiennent à Quintilian App ou à leurs auteurs respectifs.",
    "legal.liability": "Responsabilité",
    "legal.liability_content":
      "Quintilian App s'efforce de fournir des informations exactes mais ne peut garantir l'exactitude, la complétude ou l'actualité des informations diffusées sur ce site.",

    // Politique de confidentialité
    "legal.data_collection": "Collecte des données",
    "legal.data_collection_content":
      "Nous collectons uniquement les données nécessaires au fonctionnement de notre service d'analyse de réputation en ligne.",
    "legal.data_usage": "Utilisation des données",
    "legal.data_usage_content":
      "Vos données sont utilisées exclusivement pour fournir nos services d'analyse et ne sont jamais partagées avec des tiers sans votre consentement.",
    "legal.cookies": "Cookies",
    "legal.cookies_content":
      "Notre site utilise des cookies techniques nécessaires au bon fonctionnement du service. Aucun cookie de tracking n'est utilisé.",
    "legal.user_rights": "Vos droits",
    "legal.user_rights_content":
      "Conformément au RGPD, vous disposez d'un droit d'accès, de rectification, de suppression et de portabilité de vos données personnelles.",
    "legal.contact_privacy": "Contact",
    "legal.contact_privacy_content":
      "Pour toute question relative à la protection de vos données, contactez-nous à : contact@quintilian.app",

    // CGU
    "legal.acceptance": "Acceptation des conditions",
    "legal.acceptance_content":
      "L'utilisation de ce site implique l'acceptation pleine et entière des conditions générales d'utilisation décrites ci-après.",
    "legal.service_description": "Description du service",
    "legal.service_description_content":
      "Quintilian App propose un service d'analyse de réputation en ligne utilisant l'intelligence artificielle pour évaluer votre présence digitale.",
    "legal.user_obligations": "Obligations de l'utilisateur",
    "legal.user_obligations_content":
      "L'utilisateur s'engage à utiliser le service de manière conforme à la loi et à ne pas porter atteinte aux droits de tiers.",
    "legal.service_availability": "Disponibilité du service",
    "legal.service_availability_content":
      "Nous nous efforçons d'assurer une disponibilité maximale du service mais ne pouvons garantir un accès ininterrompu.",
    "legal.modifications": "Modifications",
    "legal.modifications_content":
      "Ces conditions peuvent être modifiées à tout moment. Les utilisateurs seront informés des changements importants.",

    // Info Modal
    "info.title": "Comment sont calculés vos scores ?",
    "info.presence_title": "Score de Présence",
    "info.presence_desc": "Mesure votre visibilité dans les moteurs de recherche et les IA.",
    "info.presence_item1": "Indexation Google",
    "info.presence_item2": "Mentions dans les IA",
    "info.presence_item3": "Autorité du domaine",
    "info.presence_item4": "Backlinks de qualité",
    "info.presence_item5": "Présence réseaux sociaux",
    "info.tone_title": "Score de Tonalité",
    "info.tone_desc": "Analyse l'émotion dominante de vos contenus.",
    "info.tone_item1": "Sentiment positif/négatif",
    "info.tone_item2": "Mots-clés émotionnels",
    "info.tone_item3": "Ton professionnel",
    "info.tone_item4": "Cohérence émotionnelle",
    "info.tone_item5": "Impact sur l'audience",
    "info.coherence_title": "Score de Cohérence",
    "info.coherence_desc": "Évalue l'uniformité de votre message.",
    "info.coherence_item1": "Consistance du message",
    "info.coherence_item2": "Alignement multi-canaux",
    "info.coherence_item3": "Clarté du positionnement",
    "info.coherence_item4": "Credibilité des informations",
    "info.coherence_item5": "Logique narrative",
    "info.scale_title": "Échelle de notation",
    "info.excellent": "80-100 : Excellent",
    "info.good": "60-79 : Bon",
    "info.improve": "0-59 : À améliorer",

    // Duel
    "duel.title": "Mode Duel",
    "duel.subtitle": "Comparez deux noms ou marques dans le même contexte",
    "duel.name1_placeholder": "Premier nom / marque",
    "duel.name2_placeholder": "Deuxième nom / marque",
    "duel.start_duel": "Commencer le duel",
    "duel.analyzing": "Duel en cours...",
    "duel.results": "Résultats du Duel",
    "duel.winner": "remporte le duel !",
    "duel.global_score": "Score global :",
    "duel.presence": "Présence",
    "duel.sentiment": "Tonalité",
    "duel.coherence": "Cohérence",
    "duel.global": "Score Global",
    "duel.winner_badge": "Vainqueur",
    "duel.comparative_analysis": "Analyse Comparative",
    "duel.vs": "VS",
    "duel.progress": "Progression",

    // Analysis Form
    "analysis.form_title": "Commencez votre analyse",
    "analysis.form_desc": "Remplissez les informations ci-dessous pour analyser votre présence digitale",
    "analysis.name_label": "Nom / Brand à analyser",
    "analysis.name_placeholder": "Mon identité, mon entreprise, ma marque...",
    "analysis.message_label": "Message (optionnel)",
    "analysis.message_placeholder": "Vérifiez si cette phrase matche avec votre identité en ligne",
    "analysis.language_label": "Langue",
    "analysis.language_placeholder": "Sélectionnez une langue",
    "analysis.analyzing": "Analyse en cours...",
    "analysis.analyze_now": "Analyser maintenant",

    // Analysis Modal
    "analysis.title": "Analyse en cours...",
    "analysis.google_search": "Recherche Google",
    "analysis.ai_analysis": "Analyse IA",
    "analysis.calculating": "Calcul des scores",
    "analysis.complete": "Analyse terminée",
    "analysis.results": "Résultats de l'analyse",
    "analysis.google_summary": "Résumé Google",
    "analysis.ai_summary": "Résumé IA",
    "analysis.detailed_analysis": "Analyse Complète",

    // Languages
    "lang.french": "Français",
    "lang.english": "Anglais",
    "lang.spanish": "Espagnol",
    "lang.german": "Allemand",
    "lang.italian": "Italien",
    "lang.portuguese": "Portugais",
    "lang.dutch": "Néerlandais",
    "lang.russian": "Russe",
    "lang.chinese": "Chinois",
    "lang.japanese": "Japonais",
    "lang.arabic": "Arabe",
    "lang.hindi": "Hindi",
    "lang.korean": "Coréen",
    "lang.swedish": "Suédois",
    "lang.norwegian": "Norvégien",

    // Solutions Page
    "solutions.title": "Nos Solutions",
    "solutions.subtitle":
      "Votre score ne vous satisfait pas ? Vous voulez influer dessus ? Nous avons les solutions qu'il vous faut.",
    "solutions.hero_title": "Transformez votre présence digitale",
    "solutions.hero_desc": "Des solutions personnalisées pour améliorer vos scores de présence, tonalité et cohérence.",
    "solutions.audit_title": "Audit Complet",
    "solutions.audit_desc": "Analyse approfondie de votre écosystème digital avec recommandations personnalisées.",
    "solutions.optimization_title": "Optimisation SEO",
    "solutions.optimization_desc": "Amélioration de votre visibilité sur Google et les moteurs de recherche.",
    "solutions.content_title": "Stratégie de Contenu",
    "solutions.content_desc": "Création d'une ligne éditoriale cohérente pour renforcer votre message.",
    "solutions.reputation_title": "Gestion de Réputation",
    "solutions.reputation_desc": "Monitor and improve your online brand image.",
    "solutions.cta_title": "Prêt à améliorer vos scores ?",
    "solutions.cta_desc": "Contactez notre équipe d'experts pour une consultation personnalisée.",
    "solutions.contact_button": "Demander une consultation",

    // Duel CTA
    "duel_cta.title": "Vous avez un concurrent, un adversaire, ou vous êtes simplement curieux ?",
    "duel_cta.subtitle": "Testez le mode duel et comparez votre réputation en ligne avec celle des autres",
    "duel_cta.button": "Lancer un Duel",

    "duel_announcement.title": "🔥 NOUVEAU : Mode Duel !",
    "duel_announcement.description": "Vous avez un concurrent ? Ou vous voulez vous comparer ? Testez le mode duel !",
    "duel_announcement.cta": "Essayer maintenant",

    // Solutions Page - Complete translations
    "solutions.page_title": "Quintilian Solutions",
    "solutions.page_subtitle": "Digital Reputation",
    "solutions.nav_solutions": "Solutions",
    "solutions.nav_method": "Méthode",
    "solutions.nav_contact": "Contact",
    "solutions.demo_button": "Demander une démo",
    "solutions.hero_main_title": "Maîtrisez votre réputation digitale avec IA et SEO",
    "solutions.hero_main_desc":
      "Quintilian Solutions combine SEO intelligent, analyse IA et influence sociale pour renforcer votre visibilité et votre crédibilité.",
    "solutions.discover_button": "Découvrir nos solutions",
    "solutions.dashboard_title": "Dashboard Analytics",
    "solutions.our_solutions": "Nos solutions",
    "solutions.systemic_approach":
      "Une approche systémique pour dominer votre écosystème digital et neutraliser les menaces",

    // Dashboard Analytics Module
    "solutions.dashboard_analytics_title": "Dashboard Analytics - Réputation en Temps Réel",
    "solutions.dashboard_analytics_desc":
      "Bénéficiez de votre dashboard analytics de votre réputation en ligne en temps réel",
    "solutions.essential_metrics": "Métriques Essentielles",
    "solutions.ai_presence": "Présence IA - Visibilité dans les réponses GPT et IA",
    "solutions.seo_presence": "Présence SEO - Positionnement moteurs de recherche",
    "solutions.press_impact": "Impact Presse - Couverture médiatique et mentions",
    "solutions.behavioral_analysis": "Analyse Comportementale",
    "solutions.social_presence": "Présence Réseaux Sociaux - Engagement et portée",
    "solutions.sentiment": "Sentiment - Analyse tonalité et perception",
    "solutions.message_coherence": "Cohérence Message - Alignement narratif global",
    "solutions.monitoring_247": "⚡ Monitoring 24/7 avec alertes instantanées et recommandations IA personnalisées",

    // 4 Action Modules
    "solutions.four_modules_title": "Nos 4 modules d'action",
    "solutions.four_modules_desc": "Solutions opérationnelles pour transformer votre présence digitale",

    // Module H
    "solutions.module_h_title": "Module H - Duplication Instantanée",
    "solutions.module_h_desc": "Déploiement instantané de contenu dans un réseau de sites dans 103 pays et 35 langues",
    "solutions.module_h_feature1": "Influence sur les algorithmes GPT",
    "solutions.module_h_feature2": "Impact SEO massif et instantané",
    "solutions.module_h_feature3": "Réseau de sites d'autorité mondial",
    "solutions.module_h_feature4": "Déploiement multilingue automatisé",

    // Module A
    "solutions.module_a_title": "Module A - Défense Sociale",
    "solutions.module_a_desc": "Système de défense et promotion sur les réseaux sociaux, principalement X",
    "solutions.module_a_feature1": "Impact SEO via signaux sociaux",
    "solutions.module_a_feature2": "Influence sur recherches réseaux",
    "solutions.module_a_feature3": "Modification des algorithmes IA",
    "solutions.module_a_feature4": "Stratégie défensive automatisée",

    // Module C
    "solutions.module_c_title": "Module C - Autorité Premium",
    "solutions.module_c_desc": "Réseau de sites premium et d'autorité pour légitimité réelle et durable",
    "solutions.module_c_feature1": "Implémentation durable SEO",
    "solutions.module_c_feature2": "Influence sur GPT et IA",
    "solutions.module_c_feature3": "Sites haute autorité de domaine",
    "solutions.module_c_feature4": "Légitimité institutionnelle",

    // Module P
    "solutions.module_p_title": "Module P - Sur Mesure",
    "solutions.module_p_desc": "Opérateurs spécialisés en OSINT et techniques avancées d'influence",
    "solutions.module_p_feature1": "Analyse OSINT approfondie",
    "solutions.module_p_feature2": "Enjeux humains et psychologiques",
    "solutions.module_p_feature3": "Techniques d'influence avancées",
    "solutions.module_p_feature4": "Stratégie personnalisée sur mesure",

    // Why Us Section
    "solutions.why_us_title": "Pourquoi nous ?",
    "solutions.why_us_desc": "Une expertise unique au service de votre réputation digitale",
    "solutions.increased_visibility": "Visibilité accrue",
    "solutions.increased_visibility_desc": "Positionnement optimal sur Google et moteurs de recherche",
    "solutions.controlled_reputation": "Réputation maîtrisée",
    "solutions.controlled_reputation_desc": "Contrôle total de votre image digitale et narrative",
    "solutions.measurable_influence": "Influence mesurable",
    "solutions.measurable_influence_desc": "ROI transparent avec métriques précises et KPIs",
    "solutions.digital_strategy": "Stratégie Digitale",
    "solutions.approach_360": "Approche 360°",

    // Final CTA
    "solutions.final_cta_title": "Renforcez votre présence en ligne dès aujourd'hui",
    "solutions.final_cta_desc": "Découvrez comment nos solutions peuvent transformer votre réputation digitale",
    "solutions.take_contact": "Prendre contact",

    // Footer
    "solutions.footer_legal": "Mentions légales",
    "solutions.footer_privacy": "Politique de confidentialité",
    "solutions.footer_contact": "Contact",

    "admin.dashboard_title": "Dashboard Analytics",
    "admin.dashboard_desc": "Analyse avancée des performances SEO",
    "admin.active_users": "Utilisateurs actifs",
    "admin.real_time": "En temps réel",
    "admin.searches_per_min": "Recherches/min",
    "admin.last_minute": "Dernière minute",
    "admin.response_time": "Temps de réponse",
    "admin.current_average": "Moyenne actuelle",
    "admin.error_rate": "Taux d'erreur",
    "admin.last_hour": "Dernière heure",
    "admin.password": "Mot de passe",
    "admin.login": "Connexion",
    "admin.presence": "Présence",
    "admin.sentiment": "Sentiment",
    "admin.coherence": "Cohérence",
    "admin.results": "Résultats",
    "admin.tokens": "Tokens",
    "admin.access_admin": "Accès Admin",
    "admin.enter_password": "Entrez le mot de passe pour accéder au dashboard",
    "admin.connect": "Se connecter",
    "admin.back_home": "Retour à l'accueil",
    "admin.incorrect_password": "Mot de passe incorrect",

    "duel.configuration": "Configuration du Duel",
    "duel.first_competitor": "Premier concurrent",
    "duel.second_competitor": "Deuxième concurrent",
    "duel.message_to_analyze": "Message à analyser",
    "duel.analysis_language": "Langue d'analyse",
    "duel.launch_duel": "Lancer le Duel",

    // Concept Section
    "concept.title": "Découvrez l'image que vous projetez en ligne",
    "concept.intro":
      "Un citoyen, un consommateur, un banquier, un collaborateur ou un employeur… Tous ont un premier réflexe avant de vous faire confiance : taper votre nom ou celui de votre marque sur internet.",
    "concept.questions": "Que vont-ils voir ? Que vont-ils ressentir ? Et surtout, qu'en concluront-ils ?",
    "concept.analysis":
      "C'est exactement ce que nous analysons avec nos outils. Notre outil vous permet de savoir quelle image vous renvoyez lorsqu'on effectue une recherche rapide sur vous ou votre organisation.",
    "concept.measurement":
      "Nous mesurons la présence, la tonalité et la cohérence narrative de vos résultats sur deux canaux décisifs :",
    "concept.seo_channel": "les moteurs de recherche (SEO)",
    "concept.ai_channel": "les IA conversationnelles (GPT et autres)",
    "concept.objective":
      "L'objectif n'est pas de dresser une analyse psychologique ou exhaustive de qui vous êtes réellement, mais de révéler la perception immédiate que les outils numériques construisent autour de votre identité.",
    "concept.summary": "En un mot : ce que les autres voient quand ils vous cherchent.",
    "concept.back_home": "Retour à l'accueil",
    "concept.hero_title": "Découvrez l'image que vous projetez en ligne",
    "concept.hero_subtitle":
      "Dans un monde numérique où votre réputation se construit à chaque recherche, comprenez comment vous êtes perçu par vos clients, partenaires et concurrents.",
    "concept.first_reflex_title": "Le premier réflexe de tous",
    "concept.first_reflex_text":
      "Un citoyen, un consommateur, un banquier, un collaborateur, ou un concurrent. Tous ont un premier réflexe avant de vous faire confiance :",
    "concept.first_reflex_bold": "taper votre nom ou celui de votre marque sur internet",
    "concept.what_will_they_see": "Que vont-ils voir ?",
    "concept.what_will_they_see_desc": "Les premiers résultats qui apparaissent définissent votre image",
    "concept.what_will_they_feel": "Que vont-ils ressentir ?",
    "concept.what_will_they_feel_desc": "L'émotion transmise par vos contenus influence leur décision",
    "concept.what_will_they_conclude": "Qu'en concluront-ils ?",
    "concept.what_will_they_conclude_desc": "Leur impression finale détermine s'ils vous font confiance",
    "concept.analysis_title": "C'est exactement ce que nous analysons",
    "concept.methodology_tagline": "Une méthodologie unique, un algorithme robuste",
    "concept.analysis_subtitle":
      "Notre technologie scrute l'ensemble de votre écosystème digital pour vous révéler votre véritable image en ligne.",
    "concept.quintilian_quote":
      "« Aujourd'hui, quand on cherche une information, on ne se limite plus au moteur de recherche classique. On interroge aussi les grands modèles d'intelligence artificielle, qui deviennent une nouvelle porte d'entrée vers le savoir. Or, ces deux sources donnent des visions différentes : l'une reflète ce qui existe réellement en ligne, l'autre reflète ce qui est perçu et structuré dans sa mémoire. Quintilian combine les deux pour révéler ce que \"le web\" pense vraiment de vous. Le système délivre trois scores clairs : présence, sentiment et cohérence. »",
    "concept.search_engines": "Moteurs de recherche",
    "concept.seo": "(SEO)",
    "concept.search_engines_desc":
      "Analyse complète de votre visibilité sur Google, Bing et autres moteurs de recherche",
    "concept.conversational_ai": "IA conversationnelles",
    "concept.gpt_others": "(GPT et autres)",
    "concept.conversational_ai_desc": "Évaluation de votre réputation auprès des intelligences artificielles",
    "concept.cta_button": "Analyser ma réputation maintenant",
  },
  en: {
    // Header
    "header.features": "Features",
    "header.duel": "Duel Mode",
    "header.pricing": "Pricing",
    "header.contact": "Contact",
    "header.try_free": "Try for Free",

    // GMI Page
    "gmi.title": "Global Market Intelligence",
    "gmi.subtitle": "Discover your reputation worldwide",
    "gmi.description":
      "Analyze your digital presence in up to 5 countries simultaneously and discover where you have the best reputation",
    "gmi.search_title": "Search to analyze",
    "gmi.search_description": "Enter the name of the brand, person or entity to analyze",
    "gmi.search_label": "Search term",
    "gmi.search_placeholder": "Ex: Tesla, Elon Musk, Paris...",
    "gmi.country_selection": "Country selection",
    "gmi.country_description": "Choose up to 5 countries for your analysis",
    "gmi.selected_countries": "Selected countries:",
    "gmi.analyze_button": "Analyze global reputation",
    "gmi.analyzing": "Analyzing...",
    "gmi.estimated_cost": "Estimated cost: {count} Google requests",
    "gmi.geo_analysis_title": "Geolocated Analysis",
    "gmi.geo_analysis_desc": "Get country-specific results through Google search geolocation",
    "gmi.targeted_analysis_title": "Targeted Analysis",
    "gmi.targeted_analysis_desc": "Maximum 5 countries per analysis with precise and detailed results for each region",
    "gmi.detailed_comparison_title": "Detailed Comparison",
    "gmi.detailed_comparison_desc":
      "Detailed reputation scores with comparative analysis to identify your best markets",

    // Countries
    "country.france": "France",
    "country.germany": "Germany",
    "country.spain": "Spain",
    "country.italy": "Italy",
    "country.uk": "United Kingdom",
    "country.uae": "United Arab Emirates",
    "country.saudi": "Saudi Arabia",
    "country.japan": "Japan",
    "country.china": "China",
    "country.usa": "United States",
    "country.canada": "Canada",
    "country.argentina": "Argentina",
    "country.brazil": "Brazil",
    "country.south_africa": "South Africa",
    "country.congo": "D.R. Congo",
    "country.india": "India",
    "country.australia": "Australia",

    // Hero Section
    "hero.badge": "Instant SEO Analysis Powered by AI",
    "hero.title_measure": "Measure",
    "hero.title_reputation": "your online image",
    "hero.title_time": "in one minute",
    "hero.subtitle": "3 scores, clear results",
    "hero.title": "Measure your online image in one minute - 3 scores, clear results",
    "hero.subtitle_desc":
      "Instantly discover how Google and AI perceive your name or brand: visibility, tone, and consistency.",
    "hero.name_label": "Name / Brand",
    "hero.name_placeholder": "My identity, my company, my brand...",
    "hero.message_label": "Message",
    "hero.message_placeholder": "Check if this phrase matches your online identity",
    "hero.language_label": "Analysis language",
    "hero.language_placeholder": "Select a language",
    "hero.analyze_button": "Analyze now",
    "hero.result_time": "Results in 60 seconds",
    "hero.secure": "Free and secure",
    "hero.instant_analysis": "Instant Analysis",
    "hero.detailed_results": "Detailed results in 60 seconds",

    // Features Section
    "features.title": "3 scores to understand your impact",
    "features.subtitle": "Complete analysis of your digital presence in seconds",
    "features.presence_title": "Presence score",
    "features.presence_subtitle": "SEO + GPT visibility",
    "features.presence_desc": "See if you exist where your customers and AIs are looking for you.",
    "features.tone_title": "Tone score",
    "features.tone_subtitle": "positive/negative",
    "features.tone_desc": "Understand the dominant emotion conveyed by your content.",
    "features.coherence_title": "Narrative coherence score",
    "features.coherence_subtitle": "message uniformity",
    "features.coherence_desc": "Measures the plausibility and uniformity of your message.",

    // Use Cases
    "usecases.title": "Who is it for?",
    "usecases.subtitle": "A tool adapted for everyone",
    "usecases.companies": "Companies",
    "usecases.companies_desc": "Monitor your competitors and protect your reputation against attacks.",
    "usecases.media": "Media",
    "usecases.media_desc": "Frame editorial tone and detect adverse campaigns.",
    "usecases.individuals": "Individuals",
    "usecases.individuals_desc": "Defend your personal image against disinformation.",
    "usecases.agencies": "Communication agencies",
    "usecases.agencies_desc": "Competitive intelligence and information warfare for your clients.",

    // Example Section
    "example.title": "Example result",
    "example.subtitle": "Here's what your scores look like once the analysis is complete",
    "example.presence": "Presence",
    "example.tone": "Tone",
    "example.coherence": "Coherence",
    "example.scale": "Scale:",
    "example.how_calculated": "See how it's calculated",
    "example.simple_mode": "Simple Mode",
    "example.duel_mode": "Duel Mode",
    "example.company_name": "TechCorp Solutions",
    "example.analysis_date": "Analyzed on January 15, 2025",
    "example.global_score": "Global Score",
    "example.key_metrics": "Key Metrics",
    "example.search_volume": "Monthly search volume",
    "example.brand_mentions": "Brand mentions",
    "example.sentiment_evolution": "Sentiment evolution (30d)",
    "example.strategic_recommendations": "Strategic Recommendations",
    "example.rec1_title": "Optimize SEO content",
    "example.rec1_desc": "Create 15 targeted articles on your main keywords",
    "example.rec1_impact": "Estimated impact: +25% visibility",
    "example.rec2_title": "Strengthen social presence",
    "example.rec2_desc": "Increase LinkedIn posting frequency",
    "example.rec2_impact": "Estimated impact: +18% engagement",
    "example.threat_analysis": "Threat Analysis",
    "example.threat1": "Direct competitor with better SEO",
    "example.threat2": "Negative mentions on specialized forums",
    "example.threat3": "Absence on certain key channels",
    "example.duel_title": "Nike vs Adidas - Comparative Analysis",
    "example.market_context": "Market Context",
    "example.market_desc": "Premium sportswear sector, intense competition on innovation and brand image",
    "example.category_analysis": "Category Analysis",
    "example.seo_performance": "SEO Performance",
    "example.social_presence": "Social Presence",
    "example.brand_perception": "Brand Perception",
    "example.content_quality": "Content Quality",
    "example.competitive_intelligence": "Competitive Intelligence",
    "example.nike_strengths": "Nike Strengths",
    "example.nike_strength1": "Constant product innovation",
    "example.nike_strength2": "Premium athlete partnerships",
    "example.nike_strength3": "Strong emotional storytelling",
    "example.adidas_strengths": "Adidas Strengths",
    "example.adidas_strength1": "Authentic sports heritage",
    "example.adidas_strength2": "Fashion/streetwear collaborations",
    "example.adidas_strength3": "Sustainable development commitment",
    "example.nike_weaknesses": "Nike Weaknesses",
    "example.nike_weakness1": "Recurring ethical controversies",
    "example.nike_weakness2": "Premium pricing limiting accessibility",
    "example.adidas_weaknesses": "Adidas Weaknesses",
    "example.adidas_weakness1": "Innovation perceived as less disruptive",
    "example.adidas_weakness2": "Less aggressive digital presence",

    // Pricing
    "pricing.title": "Simple and transparent pricing",
    "pricing.subtitle": "Start free, scale according to your needs",
    "pricing.free_title": "Free",
    "pricing.free_price": "€0",
    "pricing.free_period": "/month",
    "pricing.free_feature1": "1 analysis per day",
    "pricing.free_feature2": "Basic scores",
    "pricing.free_feature3": "7-day history",
    "pricing.free_feature4": "Community support",
    "pricing.free_cta": "Get Started",
    "pricing.pro_title": "Pro",
    "pricing.pro_price": "€899",
    "pricing.pro_period": "/month",
    "pricing.pro_feature1": "15 analyses per day",
    "pricing.pro_feature2": "Detailed scores + insights",
    "pricing.pro_feature3": "Unlimited history",
    "pricing.pro_feature4": "PDF reports",
    "pricing.pro_feature5": "Priority support",
    "pricing.pro_feature6": "API access",
    "pricing.pro_cta": "Contact sales",
    "pricing.ultimate_title": "Ultimate",
    "pricing.ultimate_price": "Custom quote",
    "pricing.ultimate_feature1": "Unlimited analyses",
    "pricing.ultimate_feature2": "Advanced scores + custom AI",
    "pricing.ultimate_feature3": "Complete API integration",
    "pricing.ultimate_feature4": "Custom reports",
    "pricing.ultimate_feature5": "Dedicated 24/7 support",
    "pricing.ultimate_feature6": "Team training",
    "pricing.ultimate_feature7": "Guaranteed SLA",
    "pricing.ultimate_cta": "Request quote",
    "pricing.popular": "Popular",

    // Contact
    "contact.title": "Contact us",
    "contact.subtitle": "Not satisfied with your score? Want to influence it? We have the solutions you need.",
    "contact.form_title": "Send us a message",
    "contact.email": "Email",
    "contact.email_placeholder": "your@email.com",
    "contact.message": "Message",
    "contact.message_placeholder": "Describe your need or question...",
    "contact.send": "Send message",
    "contact.success_title": "Message sent!",
    "contact.success_desc": "We'll get back to you as soon as possible.",
    "contact.direct_email": "Or write to us directly at",
    "contact.email_required": "Email is required",
    "contact.email_invalid": "Invalid email format",
    "contact.message_required": "Message is required",

    // CTA Section
    "cta.title": "Discover your score in 1 minute",
    "cta.subtitle": "Try our analyzer for free and get your 3 scores instantly",
    "cta.button": "Try now",

    // Footer
    "footer.description": "The digital presence analysis tool that measures your impact in 3 scores.",
    "footer.quick_links": "Quick links",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.legal_mentions": "Legal notices",
    "footer.privacy": "Privacy policy",
    "footer.terms": "Terms of use",
    "footer.contact_title": "Contact",
    "footer.support": "Support available 24/7",
    "footer.copyright": "© 2025 Quintilian App. All rights reserved.",

    // Legal pages
    "legal.back_home": "Back to home",
    "legal.mentions_title": "Legal notices",
    "legal.privacy_title": "Privacy policy",
    "legal.terms_title": "Terms of use",

    // Legal notices
    "legal.editor_info": "Publisher information",
    "legal.company_address": "Address: France",
    "legal.hosting_info": "Hosting information",
    "legal.hosting_details":
      "This site is hosted by Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, United States.",
    "legal.intellectual_property": "Intellectual property",
    "legal.ip_content":
      "All content on this site (texts, images, logos, etc.) is protected by copyright and belongs to Quintilian App or their respective authors.",
    "legal.liability": "Liability",
    "legal.liability_content":
      "Quintilian App strives to provide accurate information but cannot guarantee the accuracy, completeness or timeliness of information published on this site.",

    // Privacy policy
    "legal.data_collection": "Data collection",
    "legal.data_collection_content":
      "We only collect data necessary for the operation of our online reputation analysis service.",
    "legal.data_usage": "Data usage",
    "legal.data_usage_content":
      "Your data is used exclusively to provide our analysis services and is never shared with third parties without your consent.",
    "legal.cookies": "Cookies",
    "legal.cookies_content":
      "Our site uses technical cookies necessary for the proper functioning of the service. No tracking cookies are used.",
    "legal.user_rights": "Your rights",
    "legal.user_rights_content":
      "In accordance with GDPR, you have the right to access, rectify, delete and port your personal data.",
    "legal.contact_privacy": "Contact",
    "legal.contact_privacy_content":
      "For any questions regarding the protection of your data, contact us at: contact@quintilian.app",

    // Terms of use
    "legal.acceptance": "Acceptance of terms",
    "legal.acceptance_content": "Use of this site implies full acceptance of the general terms of use described below.",
    "legal.service_description": "Service description",
    "legal.service_description_content":
      "Quintilian App offers an online reputation analysis service using artificial intelligence to evaluate your digital presence.",
    "legal.user_obligations": "User obligations",
    "legal.user_obligations_content":
      "The user undertakes to use the service in accordance with the law and not to infringe the rights of third parties.",
    "legal.service_availability": "Service availability",
    "legal.service_availability_content":
      "We strive to ensure maximum service availability but cannot guarantee uninterrupted access.",
    "legal.modifications": "Modifications",
    "legal.modifications_content":
      "These terms may be modified at any time. Users will be informed of important changes.",

    // Info Modal
    "info.title": "How are your scores calculated?",
    "info.presence_title": "Presence Score",
    "info.presence_desc": "Measures your visibility in search engines and AI.",
    "info.presence_item1": "Google indexing",
    "info.presence_item2": "AI mentions",
    "info.presence_item3": "Domain authority",
    "info.presence_item4": "Quality backlinks",
    "info.presence_item5": "Social media presence",
    "info.tone_title": "Tone Score",
    "info.tone_desc": "Analyzes the dominant emotion of your content.",
    "info.tone_item1": "Positive/negative sentiment",
    "info.tone_item2": "Emotional keywords",
    "info.tone_item3": "Professional tone",
    "info.tone_item4": "Emotional consistency",
    "info.tone_item5": "Audience impact",
    "info.coherence_title": "Coherence Score",
    "info.coherence_desc": "Evaluates the uniformity of your message.",
    "info.coherence_item1": "Message consistency",
    "info.coherence_item2": "Multi-channel alignment",
    "info.coherence_item3": "Positioning clarity",
    "info.coherence_item4": "Information credibility",
    "info.coherence_item5": "Narrative logic",
    "info.scale_title": "Rating scale",
    "info.excellent": "80-100: Excellent",
    "info.good": "60-79: Good",
    "info.improve": "0-59: Needs improvement",

    // Duel
    "duel.title": "Duel Mode",
    "duel.subtitle": "Compare two names or brands in the same context",
    "duel.name1_placeholder": "First name / brand",
    "duel.name2_placeholder": "Second name / brand",
    "duel.start_duel": "Start duel",
    "duel.analyzing": "Duel in progress...",
    "duel.results": "Duel Results",
    "duel.winner": "wins the duel!",
    "duel.global_score": "Global score:",
    "duel.presence": "Presence",
    "duel.sentiment": "Sentiment",
    "duel.coherence": "Coherence",
    "duel.global": "Global Score",
    "duel.winner_badge": "Winner",
    "duel.comparative_analysis": "Comparative Analysis",
    "duel.vs": "VS",
    "duel.progress": "Progress",

    // Analysis Form
    "analysis.form_title": "Start your analysis",
    "analysis.form_desc": "Fill in the information below to analyze your digital presence",
    "analysis.name_label": "Name / Brand to analyze",
    "analysis.name_placeholder": "My identity, my company, my brand...",
    "analysis.message_label": "Message (optional)",
    "analysis.message_placeholder": "Check if this phrase matches your online identity",
    "analysis.language_label": "Language",
    "analysis.language_placeholder": "Select a language",
    "analysis.analyzing": "Analyzing...",
    "analysis.analyze_now": "Analyze now",

    // Analysis Modal
    "analysis.title": "Analysis in progress...",
    "analysis.google_search": "Google Search",
    "analysis.ai_analysis": "AI Analysis",
    "analysis.calculating": "Calculating scores",
    "analysis.complete": "Analysis complete",
    "analysis.results": "Analysis Results",
    "analysis.google_summary": "Google Summary",
    "analysis.ai_summary": "AI Summary",
    "analysis.detailed_analysis": "Complete Analysis",

    // Languages
    "lang.french": "French",
    "lang.english": "English",
    "lang.spanish": "Spanish",
    "lang.german": "German",
    "lang.italian": "Italian",
    "lang.portuguese": "Portuguese",
    "lang.dutch": "Dutch",
    "lang.russian": "Russian",
    "lang.chinese": "Chinese",
    "lang.japanese": "Japanese",
    "lang.arabic": "Arabic",
    "lang.hindi": "Hindi",
    "lang.korean": "Korean",
    "lang.swedish": "Swedish",
    "lang.norwegian": "Norwegian",

    // Solutions Page
    "solutions.title": "Our Solutions",
    "solutions.subtitle": "Not satisfied with your score? Want to influence it? We have the solutions you need.",
    "solutions.hero_title": "Transform your digital presence",
    "solutions.hero_desc": "Personalized solutions to improve your presence, tone and coherence scores.",
    "solutions.audit_title": "Complete Audit",
    "solutions.audit_desc": "In-depth analysis of your digital ecosystem with personalized recommendations.",
    "solutions.optimization_title": "SEO Optimization",
    "solutions.optimization_desc": "Improve your visibility on Google and search engines.",
    "solutions.content_title": "Content Strategy",
    "solutions.content_desc": "Create a coherent editorial line to strengthen your message.",
    "solutions.reputation_title": "Reputation Management",
    "solutions.reputation_desc": "Monitor and improve your online brand image.",
    "solutions.cta_title": "Ready to improve your scores?",
    "solutions.cta_desc": "Contact our team of experts for a personalized consultation.",
    "solutions.contact_button": "Request consultation",

    // Duel CTA
    "duel_cta.title": "Do you have a competitor, an opponent, or are you simply curious?",
    "duel_cta.subtitle": "Test duel mode and compare your online reputation with others",
    "duel_cta.button": "Launch a Duel",

    "duel_announcement.title": "🔥 NEW: Duel Mode!",
    "duel_announcement.description": "Do you have a competitor? Or want to compare yourself? Test duel mode!",
    "duel_announcement.cta": "Try now",

    // Solutions Page - Complete translations
    "solutions.page_title": "Quintilian Solutions",
    "solutions.page_subtitle": "Digital Reputation",
    "solutions.nav_solutions": "Solutions",
    "solutions.nav_method": "Method",
    "solutions.nav_contact": "Contact",
    "solutions.demo_button": "Request a demo",
    "solutions.hero_main_title": "Master your digital reputation with AI and SEO",
    "solutions.hero_main_desc":
      "Quintilian Solutions combines intelligent SEO, AI analysis and social influence to strengthen your visibility and credibility.",
    "solutions.discover_button": "Discover our solutions",
    "solutions.dashboard_title": "Dashboard Analytics",
    "solutions.our_solutions": "Our solutions",
    "solutions.systemic_approach": "A systemic approach to dominate your digital ecosystem and neutralize threats",

    // Dashboard Analytics Module
    "solutions.dashboard_analytics_title": "Dashboard Analytics - Real-Time Reputation",
    "solutions.dashboard_analytics_desc": "Benefit from your real-time online reputation analytics dashboard",
    "solutions.essential_metrics": "Essential Metrics",
    "solutions.ai_presence": "AI Presence - Visibility in GPT and AI responses",
    "solutions.seo_presence": "SEO Presence - Search engine positioning",
    "solutions.press_impact": "Press Impact - Media coverage and mentions",
    "solutions.behavioral_analysis": "Behavioral Analysis",
    "solutions.social_presence": "Social Media Presence - Engagement and reach",
    "solutions.sentiment": "Sentiment - Tone and perception analysis",
    "solutions.message_coherence": "Message Coherence - Global narrative alignment",
    "solutions.monitoring_247": "⚡ 24/7 Monitoring with instant alerts and personalized AI recommendations",

    // 4 Action Modules
    "solutions.four_modules_title": "Our 4 action modules",
    "solutions.four_modules_desc": "Operational solutions to transform your digital presence",

    // Module H
    "solutions.module_h_title": "Module H - Instant Duplication",
    "solutions.module_h_desc": "Instant content deployment across a network of sites in 103 countries and 35 languages",
    "solutions.module_h_feature1": "Influence on GPT algorithms",
    "solutions.module_h_feature2": "Massive and instant SEO impact",
    "solutions.module_h_feature3": "Global authority sites network",
    "solutions.module_h_feature4": "Automated multilingual deployment",

    // Module A
    "solutions.module_a_title": "Module A - Social Defense",
    "solutions.module_a_desc": "Defense and promotion system on social networks, mainly X",
    "solutions.module_a_feature1": "SEO impact via social signals",
    "solutions.module_a_feature2": "Influence on network searches",
    "solutions.module_a_feature3": "AI algorithm modification",
    "solutions.module_a_feature4": "Automated defensive strategy",

    // Module C
    "solutions.module_c_title": "Module C - Premium Authority",
    "solutions.module_c_desc": "Network of premium and authority sites for real and lasting legitimacy",
    "solutions.module_c_feature1": "Sustainable SEO implementation",
    "solutions.module_c_feature2": "Influence on GPT and AI",
    "solutions.module_c_feature3": "High domain authority sites",
    "solutions.module_c_feature4": "Institutional legitimacy",

    // Module P
    "solutions.module_p_title": "Module P - Custom Made",
    "solutions.module_p_desc": "Operators specialized in OSINT and advanced influence techniques",
    "solutions.module_p_feature1": "In-depth OSINT analysis",
    "solutions.module_p_feature2": "Human and psychological issues",
    "solutions.module_p_feature3": "Advanced influence techniques",
    "solutions.module_p_feature4": "Personalized custom strategy",

    // Why Us Section
    "solutions.why_us_title": "Why us?",
    "solutions.why_us_desc": "Unique expertise at the service of your digital reputation",
    "solutions.increased_visibility": "Increased visibility",
    "solutions.increased_visibility_desc": "Optimal positioning on Google and search engines",
    "solutions.controlled_reputation": "Controlled reputation",
    "solutions.controlled_reputation_desc": "Total control of your digital image and narrative",
    "solutions.measurable_influence": "Measurable influence",
    "solutions.measurable_influence_desc": "Transparent ROI with precise metrics and KPIs",
    "solutions.digital_strategy": "Digital Strategy",
    "solutions.approach_360": "360° Approach",

    // Final CTA
    "solutions.final_cta_title": "Strengthen your online presence today",
    "solutions.final_cta_desc": "Discover how our solutions can transform your digital reputation",
    "solutions.take_contact": "Get in touch",

    // Footer
    "solutions.footer_legal": "Legal notices",
    "solutions.footer_privacy": "Privacy policy",
    "solutions.footer_contact": "Contact",

    "admin.dashboard_title": "Dashboard Analytics",
    "admin.dashboard_desc": "Advanced SEO performance analysis",
    "admin.active_users": "Active users",
    "admin.real_time": "Real time",
    "admin.searches_per_min": "Searches/min",
    "admin.last_minute": "Last minute",
    "admin.response_time": "Response time",
    "admin.current_average": "Current average",
    "admin.error_rate": "Error rate",
    "admin.last_hour": "Last hour",
    "admin.password": "Password",
    "admin.login": "Login",
    "admin.presence": "Presence",
    "admin.sentiment": "Sentiment",
    "admin.coherence": "Coherence",
    "admin.results": "Results",
    "admin.tokens": "Tokens",
    "admin.access_admin": "Admin Access",
    "admin.enter_password": "Enter password to access dashboard",
    "admin.connect": "Connect",
    "admin.back_home": "Back to home",
    "admin.incorrect_password": "Incorrect password",

    "duel.configuration": "Duel Configuration",
    "duel.first_competitor": "First competitor",
    "duel.second_competitor": "Second competitor",
    "duel.message_to_analyze": "Message to analyze",
    "duel.analysis_language": "Analysis language",
    "duel.launch_duel": "Launch Duel",

    // Concept Section
    "concept.title": "Discover the image you project online",
    "concept.intro":
      "A citizen, a consumer, a banker, a colleague, or an employer... They all have the same first reflex before trusting you: typing your name or your brand on the internet.",
    "concept.questions": "What will they see? What will they feel? And most importantly, what will they conclude?",
    "concept.analysis":
      "This is exactly what we analyze with our tools. Our tool allows you to know what image you project when someone performs a quick search about you or your organization.",
    "concept.measurement":
      "We measure the presence, tone, and narrative consistency of your results on two decisive channels:",
    "concept.seo_channel": "search engines (SEO)",
    "concept.ai_channel": "conversational AIs (GPT and others)",
    "concept.objective":
      "The objective is not to provide a psychological or exhaustive analysis of who you really are, but to reveal the immediate perception that digital tools build around your identity.",
    "concept.summary": "In a word: what others see when they search for you.",
    "concept.back_home": "Back to home",
    "concept.hero_title": "Discover the image you project online",
    "concept.hero_subtitle":
      "In a digital world where your reputation is built with every search, understand how you are perceived by your clients, partners and competitors.",
    "concept.first_reflex_title": "Everyone's first reflex",
    "concept.first_reflex_text":
      "A citizen, a consumer, a banker, a collaborator, or a competitor. They all have a first reflex before trusting you:",
    "concept.first_reflex_bold": "type your name or your brand name on the internet",
    "concept.what_will_they_see": "What will they see?",
    "concept.what_will_they_see_desc": "The first results that appear define your image",
    "concept.what_will_they_feel": "What will they feel?",
    "concept.what_will_they_feel_desc": "The emotion conveyed by your content influences their decision",
    "concept.what_will_they_conclude": "What will they conclude?",
    "concept.what_will_they_conclude_desc": "Their final impression determines whether they trust you",
    "concept.analysis_title": "This is exactly what we analyze",
    "concept.methodology_tagline": "A unique methodology, a robust algorithm",
    "concept.analysis_subtitle": "Our technology scans your entire digital ecosystem to reveal your true online image.",
    "concept.quintilian_quote":
      '« Today, when we search for information, we no longer limit ourselves to classic search engines. We also query large artificial intelligence models, which are becoming a new gateway to knowledge. However, these two sources give different visions: one reflects what actually exists online, the other reflects what is perceived and structured in its memory. Quintilian combines both to reveal what "the web" really thinks of you. The system delivers three clear scores: presence, sentiment and coherence. »',
    "concept.search_engines": "Search engines",
    "concept.seo": "(SEO)",
    "concept.search_engines_desc": "Complete analysis of your visibility on Google, Bing and other search engines",
    "concept.conversational_ai": "Conversational AI",
    "concept.gpt_others": "(GPT and others)",
    "concept.conversational_ai_desc": "Assessment of your reputation with artificial intelligences",
    "concept.cta_button": "Analyze my reputation now",
  },
  es: {
    // Header
    "header.features": "Características",
    "header.duel": "Modo Duelo",
    "header.pricing": "Precios",
    "header.contact": "Contacto",
    "header.try_free": "Prueba gratis",

    // GMI Page
    "gmi.title": "Inteligencia de Mercado Global",
    "gmi.subtitle": "Descubre tu reputación en el mundo",
    "gmi.description":
      "Analiza tu presencia digital en hasta 5 países simultáneamente y descubre dónde tienes la mejor reputación",
    "gmi.search_title": "Búsqueda a analizar",
    "gmi.search_description": "Ingresa el nombre de la marca, persona o entidad a analizar",
    "gmi.search_label": "Término de búsqueda",
    "gmi.search_placeholder": "Ej: Tesla, Elon Musk, París...",
    "gmi.country_selection": "Selección de países",
    "gmi.country_description": "Elige hasta 5 países para tu análisis",
    "gmi.selected_countries": "Países seleccionados:",
    "gmi.analyze_button": "Analizar reputación mundial",
    "gmi.analyzing": "Analizando...",
    "gmi.estimated_cost": "Costo estimado: {count} solicitudes Google",
    "gmi.geo_analysis_title": "Análisis Geolocalizado",
    "gmi.geo_analysis_desc": "Obtén resultados específicos por país a través de la geolocalización de búsquedas Google",
    "gmi.targeted_analysis_title": "Análisis Dirigido",
    "gmi.targeted_analysis_desc": "Máximo 5 países por análisis con resultados precisos y detallados para cada región",
    "gmi.detailed_comparison_title": "Comparación Detallada",
    "gmi.detailed_comparison_desc":
      "Puntuaciones de reputación detalladas con análisis comparativo para identificar tus mejores mercados",

    // Countries
    "country.france": "France",
    "country.germany": "Germany",
    "country.spain": "Spain",
    "country.italy": "Italy",
    "country.uk": "United Kingdom",
    "country.uae": "United Arab Emirates",
    "country.saudi": "Saudi Arabia",
    "country.japan": "Japan",
    "country.china": "China",
    "country.usa": "United States",
    "country.canada": "Canada",
    "country.argentina": "Argentina",
    "country.brazil": "Brazil",
    "country.south_africa": "South Africa",
    "country.congo": "D.R. Congo",
    "country.india": "India",
    "country.australia": "Australia",

    // Hero Section
    "hero.badge": "Análisis SEO Instantáneo Powered by AI",
    "hero.title_measure": "Mide",
    "hero.title_reputation": "tu imagen en línea",
    "hero.title_time": "en un minuto",
    "hero.subtitle": "3 puntuaciones, resultados claros",
    "hero.title": "Mide tu imagen en línea en un minuto - 3 puntuaciones, resultados claros",
    "hero.subtitle_desc":
      "Descubre al instante cómo Google y la IA perciben tu nombre o marca: visibilidad, tono y coherencia.",
    "hero.name_label": "Nombre / Marca",
    "hero.name_placeholder": "Mi identidad, mi empresa, mi marca...",
    "hero.message_label": "Mensaje",
    "hero.message_placeholder": "Verifica si esta frase coincide con tu identidad online",
    "hero.language_label": "Idioma de análisis",
    "hero.language_placeholder": "Selecciona un idioma",
    "hero.analyze_button": "Analizar ahora",
    "hero.result_time": "Resultado en 60 segundos",
    "hero.secure": "Gratis y seguro",
    "hero.instant_analysis": "Análisis Instantáneo",
    "hero.detailed_results": "Resultados detallados en 60 segundos",

    // Features Section
    "features.title": "3 puntuaciones para entender tu impacto",
    "features.subtitle": "Análisis completo de tu presencia digital en segundos",
    "features.presence_title": "Puntuación de presencia",
    "features.presence_subtitle": "SEO + visibilidad GPT",
    "features.presence_desc": "Ve si existes donde tus clientes y las IA te buscan.",
    "features.tone_title": "Puntuación de tono",
    "features.tone_subtitle": "positivo/negativo",
    "features.tone_desc": "Comprende la emoción dominante transmitida por tu contenido.",
    "features.coherence_title": "Puntuación de coherencia narrativa",
    "features.coherence_subtitle": "uniformidad del mensaje",
    "features.coherence_desc": "Mide la plausibilidad y uniformidad de tu mensaje.",

    // Use Cases
    "usecases.title": "¿Para quién?",
    "usecases.subtitle": "Una herramienta adaptada para todos",
    "usecases.companies": "Empresas",
    "usecases.companies_desc": "Monitorea a tus competidores y protege tu reputación contra ataques.",
    "usecases.media": "Medios",
    "usecases.media_desc": "Enmarca el tono editorial y detecta campañas adversas.",
    "usecases.individuals": "Particulares",
    "usecases.individuals_desc": "Defiende tu imagen personal contra la desinformación.",
    "usecases.agencies": "Agencias de comunicación",
    "usecases.agencies_desc": "Inteligencia competitiva y guerra informacional para tus clientes.",

    // Example Section
    "example.title": "Ejemplo de resultado",
    "example.subtitle": "Así es como se ven tus puntuaciones una vez completado el análisis",
    "example.presence": "Presencia",
    "example.tone": "Tono",
    "example.coherence": "Coherencia",
    "example.scale": "Escala:",
    "example.how_calculated": "Ver cómo se calcula",
    "example.simple_mode": "Modo Simple",
    "example.duel_mode": "Modo Duelo",
    "example.company_name": "TechCorp Solutions",
    "example.analysis_date": "Analizado el 15 de enero de 2025",
    "example.global_score": "Puntuación Global",
    "example.key_metrics": "Métricas Clave",
    "example.search_volume": "Volumen de búsqueda mensual",
    "example.brand_mentions": "Mentions de marca",
    "example.sentiment_evolution": "Evolución sentimiento (30d)",
    "example.strategic_recommendations": "Recomendaciones Estratégicas",
    "example.rec1_title": "Optimizar contenido SEO",
    "example.rec1_desc": "Crear 15 artículos dirigidos a tus palabras clave principales",
    "example.rec1_impact": "Impacto estimado: +25% visibilidad",
    "example.rec2_title": "Reforzar presencia social",
    "example.rec2_desc": "Aumentar frecuencia de publicación LinkedIn",
    "example.rec2_impact": "Impacto estimado: +18% engagement",
    "example.threat_analysis": "Análisis de Amenazas",
    "example.threat1": "Competidor directo con mejor SEO",
    "example.threat2": "Mentions negativas en foros especializados",
    "example.threat3": "Ausencia en ciertos canales clave",
    "example.duel_title": "Nike vs Adidas - Análisis Comparativo",
    "example.market_context": "Contexto de Mercado",
    "example.market_desc": "Sector sportswear premium, competencia intensa en innovación e imagen de marca",
    "example.category_analysis": "Análisis por Categoría",
    "example.seo_performance": "Rendimiento SEO",
    "example.social_presence": "Presencia Social",
    "example.brand_perception": "Percepción de Marca",
    "example.content_quality": "Calidad de Contenido",
    "example.competitive_intelligence": "Inteligencia Competitiva",
    "example.nike_strengths": "Fortalezas Nike",
    "example.nike_strength1": "Innovación constante de productos",
    "example.nike_strength2": "Asociaciones con atletas premium",
    "example.nike_strength3": "Storytelling emocional fuerte",
    "example.adidas_strengths": "Fortalezas Adidas",
    "example.adidas_strength1": "Herencia deportiva auténtica",
    "example.adidas_strength2": "Colaboraciones moda/streetwear",
    "example.adidas_strength3": "Compromiso desarrollo sostenible",
    "example.nike_weaknesses": "Debilidades Nike",
    "example.nike_weakness1": "Controversias éticas recurrentes",
    "example.nike_weakness2": "Precios premium limitando accesibilidad",
    "example.adidas_weaknesses": "Debilidades Adidas",
    "example.adidas_weakness1": "Innovación percibida como menos disruptiva",
    "example.adidas_weakness2": "Presencia digital menos agresiva",

    // Pricing
    "pricing.title": "Precios simples y transparentes",
    "pricing.subtitle": "Commencez gratuitement, évoluez selon vos besoins",
    "pricing.free_title": "Gratuit",
    "pricing.free_price": "0€",
    "pricing.free_period": "/mois",
    "pricing.free_feature1": "1 analyse par jour",
    "pricing.free_feature2": "Scores de base",
    "pricing.free_feature3": "Historique 7 jours",
    "pricing.free_feature4": "Support communautaire",
    "pricing.free_cta": "Commencer",
    "pricing.pro_title": "Pro",
    "pricing.pro_price": "899€",
    "pricing.pro_period": "/mois",
    "pricing.pro_feature1": "15 analyses par jour",
    "pricing.pro_feature2": "Scores détaillés + insights",
    "pricing.pro_feature3": "Historique illimité",
    "pricing.pro_feature4": "Rapports PDF",
    "pricing.pro_feature5": "Support prioritaire",
    "pricing.pro_feature6": "API access",
    "pricing.pro_cta": "Contacter les ventes",
    "pricing.ultimate_title": "Ultimate",
    "pricing.ultimate_price": "Sur devis",
    "pricing.ultimate_feature1": "Analyses illimitées",
    "pricing.ultimate_feature2": "Scores avancés + IA personnalisée",
    "pricing.ultimate_feature3": "Intégration API complète",
    "pricing.ultimate_feature4": "Rapports personnalisés",
    "pricing.ultimate_feature5": "Support dédié 24/7",
    "pricing.ultimate_feature6": "Formation équipe",
    "pricing.ultimate_feature7": "SLA garanti",
    "pricing.ultimate_cta": "Demander le prix",
    "pricing.popular": "Populaire",

    // Contact
    "contact.title": "Contáctanos",
    "contact.subtitle":
      "¿No estás satisfecho con tu puntuación? ¿Quieres influir en ella? Tenemos las soluciones que necesitas.",
    "contact.form_title": "Envíanos un mensaje",
    "contact.email": "Email",
    "contact.email_placeholder": "tu@email.com",
    "contact.message": "Mensaje",
    "contact.message_placeholder": "Describe tu necesidad o pregunta...",
    "contact.send": "Enviar mensaje",
    "contact.success_title": "¡Mensaje enviado!",
    "contact.success_desc": "Te responderemos lo antes posible.",
    "contact.direct_email": "O escríbenos directamente a",
    "contact.email_required": "El email es obligatorio",
    "contact.email_invalid": "Formato de email inválido",
    "contact.message_required": "El mensaje es obligatorio",

    // CTA Section
    "cta.title": "Descubre tu puntuación en 1 minuto",
    "cta.subtitle": "Prueba gratis nuestro analizador y obtén tus 3 puntuaciones al instante",
    "cta.button": "Probar ahora",

    // Footer
    "footer.description": "La herramienta de análisis de presencia digital que mide tu impacto en 3 scores.",
    "footer.quick_links": "Enlaces rápidos",
    "footer.features": "Características",
    "footer.pricing": "Precios",
    "footer.contact": "Contacto",
    "footer.legal": "Legal",
    "footer.legal_mentions": "Avisos legales",
    "footer.privacy": "Política de privacidad",
    "footer.terms": "Términos de uso",
    "footer.contact_title": "Contacto",
    "footer.support": "Soporte disponible 24/7",
    "footer.copyright": "© 2025 Quintilian App. Todos los derechos reservados.",

    // Legal pages
    "legal.back_home": "Volver al inicio",
    "legal.mentions_title": "Avisos legales",
    "legal.privacy_title": "Política de privacidad",
    "legal.terms_title": "Términos de uso",

    // Legal notices
    "legal.editor_info": "Información del editor",
    "legal.company_address": "Dirección: Francia",
    "legal.hosting_info": "Información de alojamiento",
    "legal.hosting_details":
      "Este sitio está alojado por Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, Estados Unidos.",
    "legal.intellectual_property": "Propiedad intelectual",
    "legal.ip_content":
      "Todo el contenido de este sitio (textos, imágenes, logotipos, etc.) está protegido por derechos de autor y pertenece a Quintilian App o a sus respectivos autores.",
    "legal.liability": "Responsabilidad",
    "legal.liability_content":
      "Quintilian App se esfuerza por proporcionar información precisa pero no puede garantizar la exactitud, integridad o actualidad de la información publicada en este sitio.",

    // Privacy policy
    "legal.data_collection": "Recopilación de datos",
    "legal.data_collection_content":
      "Solo recopilamos los datos necesarios para el funcionamiento de nuestro servicio de análisis de reputación online.",
    "legal.data_usage": "Uso de datos",
    "legal.data_usage_content":
      "Sus datos se utilizan exclusivamente para proporcionar nuestros servicios de análisis y nunca se comparten con terceros sin su consentimiento.",
    "legal.cookies": "Cookies",
    "legal.cookies_content":
      "Nuestro sitio utiliza cookies técnicas necesarias para el buen funcionamiento del servicio. No se utilizan cookies de seguimiento.",
    "legal.user_rights": "Sus derechos",
    "legal.user_rights_content":
      "De acuerdo con el RGPD, tiene derecho a acceder, rectificar, eliminar y portar sus datos personales.",
    "legal.contact_privacy": "Contacto",
    "legal.contact_privacy_content":
      "Para cualquier pregunta sobre la protección de sus datos, contáctenos en: contact@quintilian.app",

    // Terms of use
    "legal.acceptance": "Aceptación de términos",
    "legal.acceptance_content":
      "El uso de este sitio implica la aceptación total de los términos generales de uso descritos a continuación.",
    "legal.service_description": "Descripción del servicio",
    "legal.service_description_content":
      "Quintilian App ofrece un servicio de análisis de reputación online utilizando inteligencia artificial para evaluar su presencia digital.",
    "legal.user_obligations": "Obligaciones del usuario",
    "legal.user_obligations_content":
      "El usuario se compromete a utilizar el servicio de manera conforme a la ley y a no infringir los derechos de terceros.",
    "legal.service_availability": "Disponibilidad del servicio",
    "legal.service_availability_content":
      "Nos esforzamos por garantizar la máxima disponibilidad del servicio pero no podemos garantizar un acceso ininterrumpido.",
    "legal.modifications": "Modificaciones",
    "legal.modifications_content":
      "Estos términos pueden modificarse en cualquier momento. Los usuarios serán informados de cambios importantes.",

    // Info Modal
    "info.title": "¿Cómo se calculan tus puntuaciones?",
    "info.presence_title": "Puntuación de Presencia",
    "info.presence_desc": "Mide tu visibilidad en motores de búsqueda e IA.",
    "info.presence_item1": "Indexación Google",
    "info.presence_item2": "Menciones en IA",
    "info.presence_item3": "Autoridad del dominio",
    "info.presence_item4": "Backlinks de calidad",
    "info.presence_item5": "Presencia redes sociales",
    "info.tone_title": "Puntuación de Tono",
    "info.tone_desc": "Analiza la emoción dominante de tu contenido.",
    "info.tone_item1": "Sentimiento positivo/negativo",
    "info.tone_item2": "Palabras clave emocionales",
    "info.tone_item3": "Tono profesional",
    "info.tone_item4": "Cohérence emocional",
    "info.tone_item5": "Impacto en la audiencia",
    "info.coherence_title": "Puntuación de Coherencia",
    "info.coherence_desc": "Evalúa la uniformidad de tu mensaje.",
    "info.coherence_item1": "Consistencia del mensaje",
    "info.coherence_item2": "Alineación multicanal",
    "info.coherence_item3": "Claridad del posicionamiento",
    "info.coherence_item4": "Credibilidad de la información",
    "info.coherence_item5": "Lógica narrativa",
    "info.scale_title": "Escala de puntuación",
    "info.excellent": "80-100: Excelente",
    "info.good": "60-79: Bueno",
    "info.improve": "0-59: A mejorar",

    // Duel
    "duel.title": "Modo Duelo",
    "duel.subtitle": "Compara dos nombres o marcas en el mismo contexto",
    "duel.name1_placeholder": "Primer nombre / marca",
    "duel.name2_placeholder": "Segundo nombre / marca",
    "duel.start_duel": "Comenzar duelo",
    "duel.analyzing": "Duel en curso...",
    "duel.results": "Resultados del Duelo",
    "duel.winner": "¡gana el duelo!",
    "duel.global_score": "Puntuación global :",
    "duel.presence": "Presencia",
    "duel.sentiment": "Sentimiento",
    "duel.coherence": "Coherencia",
    "duel.global": "Puntuación Global",
    "duel.winner_badge": "Ganador",
    "duel.comparative_analysis": "Análisis Comparativo",
    "duel.vs": "VS",
    "duel.progress": "Progreso",

    // Analysis Form
    "analysis.form_title": "Comienza tu análisis",
    "analysis.form_desc": "Completa la información a continuación para analizar tu presencia digital",
    "analysis.name_label": "Nombre / Marca a analizar",
    "analysis.name_placeholder": "Mi identidad, mi empresa, mi marca...",
    "analysis.message_label": "Mensaje (opcional)",
    "analysis.message_placeholder": "Verifica si esta frase coincide con tu identidad online",
    "analysis.language_label": "Idioma",
    "analysis.language_placeholder": "Selecciona un idioma",
    "analysis.analyzing": "Analizando...",
    "analysis.analyze_now": "Analizar ahora",

    // Analysis Modal
    "analysis.title": "Análisis en curso...",
    "analysis.google_search": "Búsqueda Google",
    "analysis.ai_analysis": "Análisis IA",
    "analysis.calculating": "Calculando puntuaciones",
    "analysis.complete": "Análisis completado",
    "analysis.results": "Resultados del Análisis",
    "analysis.google_summary": "Resumen Google",
    "analysis.ai_summary": "Resumen IA",
    "analysis.detailed_analysis": "Análisis Completo",

    // Languages
    "lang.french": "Francés",
    "lang.english": "Inglés",
    "lang.spanish": "Español",
    "lang.german": "Alemán",
    "lang.italian": "Italiano",
    "lang.portuguese": "Portugués",
    "lang.dutch": "Holandés",
    "lang.russian": "Ruso",
    "lang.chinese": "Chino",
    "lang.japanese": "Japonés",
    "lang.arabic": "Árabe",
    "lang.hindi": "Hindi",
    "lang.korean": "Coreano",
    "lang.swedish": "Sueco",
    "lang.norwegian": "Noruego",

    // Solutions Page
    "solutions.title": "Nuestras Soluciones",
    "solutions.subtitle":
      "¿No estás satisfecho con tu puntuación? ¿Quieres influir en ella? Tenemos las soluciones que necesitas.",
    "solutions.hero_title": "Transforma tu presencia digital",
    "solutions.hero_desc": "Soluciones personalizadas para mejorar tus puntuaciones de presencia, tono y coherencia.",
    "solutions.audit_title": "Auditoría Completa",
    "solutions.audit_desc": "Análisis profundo de tu ecosistema digital con recomendaciones personalizadas.",
    "solutions.optimization_title": "Optimización SEO",
    "solutions.optimization_desc": "Mejora tu visibilidad en Google y motores de búsqueda.",
    "solutions.content_title": "Estrategia de Contenido",
    "solutions.content_desc": "Creación de una línea editorial coherente para fortalecer tu mensaje.",
    "solutions.reputation_title": "Gestión de Reputación",
    "solutions.reputation_desc": "Monitor and improve your online brand image.",
    "solutions.cta_title": "¿Listo para mejorar tus puntuaciones?",
    "solutions.cta_desc": "Contacta a nuestro equipo de expertos para una consulta personalizada.",
    "solutions.contact_button": "Solicitar consulta",

    // Duel CTA
    "duel_cta.title": "Vous avez un concurrent, un adversaire, ou vous êtes simplement curieux ?",
    "duel_cta.subtitle": "Testez le mode duel et comparez votre réputation en ligne avec celle des autres",
    "duel_cta.button": "Lancer un Duel",

    "duel_announcement.title": "🔥 NUEVO: ¡Modo Duelo!",
    "duel_announcement.description": "¿Tienes un competidor? ¿O quieres compararte? ¡Prueba el modo duelo!",
    "duel_announcement.cta": "Probar ahora",

    // Solutions Page - Complete translations
    "solutions.page_title": "Quintilian Solutions",
    "solutions.page_subtitle": "Reputación Digital",
    "solutions.nav_solutions": "Soluciones",
    "solutions.nav_method": "Método",
    "solutions.nav_contact": "Contacto",
    "solutions.demo_button": "Solicitar una demo",
    "solutions.hero_main_title": "Domina tu reputación digital con IA y SEO",
    "solutions.hero_main_desc":
      "Quintilian Solutions combina SEO inteligente, análisis de IA e influencia social para fortalecer tu visibilidad y credibilidad.",
    "solutions.discover_button": "Descubrir nuestras solutions",
    "solutions.dashboard_title": "Dashboard Analytics",
    "solutions.our_solutions": "Nuestras soluciones",
    "solutions.systemic_approach": "Un enfoque sistémico para dominar tu ecosistema digital y neutralizar amenazas",

    // Dashboard Analytics Module
    "solutions.dashboard_analytics_title": "Dashboard Analytics - Reputación en Tiempo Real",
    "solutions.dashboard_analytics_desc":
      "Benefíciate de tu dashboard analytics de tu reputación online en tiempo real",
    "solutions.essential_metrics": "Métricas Esenciales",
    "solutions.ai_presence": "Presencia IA - Visibilidad en respuestas GPT e IA",
    "solutions.seo_presence": "Presencia SEO - Posicionamiento en motores de búsqueda",
    "solutions.press_impact": "Impacto Prensa - Cobertura mediática y menciones",
    "solutions.behavioral_analysis": "Análisis Comportamental",
    "solutions.social_presence": "Presencia Redes Sociales - Engagement y alcance",
    "solutions.sentiment": "Sentimiento - Análisis de tono y percepción",
    "solutions.message_coherence": "Coherencia Mensaje - Alineación narrativa global",
    "solutions.monitoring_247": "⚡ Monitoreo 24/7 con alertas instantáneas y recomendaciones IA personalizadas",

    // 4 Action Modules
    "solutions.four_modules_title": "Nuestros 4 módulos de acción",
    "solutions.four_modules_desc": "Soluciones operacionales para transformar tu presencia digital",

    // Module H
    "solutions.module_h_title": "Módulo H - Duplicación Instantánea",
    "solutions.module_h_desc": "Despliegue instantáneo de contenido en una red de sitios en 103 países y 35 idiomas",
    "solutions.module_h_feature1": "Influencia en algoritmos GPT",
    "solutions.module_h_feature2": "Impacto SEO masivo e instantáneo",
    "solutions.module_h_feature3": "Red mundial de sitios de autoridad",
    "solutions.module_h_feature4": "Despliegue multilingüe automatizado",

    // Module A
    "solutions.module_a_title": "Módulo A - Defensa Social",
    "solutions.module_a_desc": "Sistema de defensa y promoción en redes sociales, principalmente X",
    "solutions.module_a_feature1": "Impacto SEO vía señales sociales",
    "solutions.module_a_feature2": "Influencia en búsquedas de redes",
    "solutions.module_a_feature3": "Modificación de algoritmos IA",
    "solutions.module_a_feature4": "Estrategia defensiva automatizada",

    // Module C
    "solutions.module_c_title": "Módulo C - Autoridad Premium",
    "solutions.module_c_desc": "Red de sitios premium y de autoridad para legitimidad real y duradera",
    "solutions.module_c_feature1": "Implementación SEO sostenible",
    "solutions.module_c_feature2": "Influencia en GPT e IA",
    "solutions.module_c_feature3": "Sitios de alta autoridad de dominio",
    "solutions.module_c_feature4": "Legitimidad institucional",

    // Module P
    "solutions.module_p_title": "Módulo P - A Medida",
    "solutions.module_p_desc": "Operadores especializados en OSINT y técnicas avanzadas de influencia",
    "solutions.module_p_feature1": "Análisis OSINT profundo",
    "solutions.module_p_feature2": "Aspectos humanos y psicológicos",
    "solutions.module_p_feature3": "Técnicas de influencia avanzadas",
    "solutions.module_p_feature4": "Estrategia personalizada a medida",

    // Why Us Section
    "solutions.why_us_title": "¿Por qué nosotros?",
    "solutions.why_us_desc": "Una experiencia única al servicio de tu reputación digital",
    "solutions.increased_visibility": "Visibilidad aumentada",
    "solutions.increased_visibility_desc": "Posicionamiento óptimo en Google y motores de búsqueda",
    "solutions.controlled_reputation": "Reputación controlada",
    "solutions.controlled_reputation_desc": "Control total de tu imagen digital y narrativa",
    "solutions.measurable_influence": "Influencia medible",
    "solutions.measurable_influence_desc": "ROI transparente con métricas precisas y KPIs",
    "solutions.digital_strategy": "Estrategia Digital",
    "solutions.approach_360": "Enfoque 360°",

    // Final CTA
    "solutions.final_cta_title": "Fortalece tu presencia online hoy",
    "solutions.final_cta_desc": "Descubre cómo nuestras soluciones pueden transformar tu reputación digital",
    "solutions.take_contact": "Ponerse en contacto",

    // Footer
    "solutions.footer_legal": "Avisos legales",
    "solutions.footer_privacy": "Política de privacidad",
    "solutions.footer_contact": "Contacto",

    "admin.dashboard_title": "Dashboard Analytics",
    "admin.dashboard_desc": "Análisis avanzado de rendimiento SEO",
    "admin.active_users": "Usuarios activos",
    "admin.real_time": "Tiempo real",
    "admin.searches_per_min": "Búsquedas/min",
    "admin.last_minute": "Último minuto",
    "admin.response_time": "Tiempo de respuesta",
    "admin.current_average": "Promedio actual",
    "admin.error_rate": "Tasa de error",
    "admin.last_hour": "Última hora",
    "admin.password": "Contraseña",
    "admin.login": "Iniciar sesión",
    "admin.presence": "Presencia",
    "admin.sentiment": "Sentimiento",
    "admin.coherence": "Coherencia",
    "admin.results": "Resultados",
    "admin.tokens": "Tokens",
    "admin.access_admin": "Acceso Admin",
    "admin.enter_password": "Ingrese la contraseña para acceder al dashboard",
    "admin.connect": "Conectar",
    "admin.back_home": "Volver al inicio",
    "admin.incorrect_password": "Contraseña incorrecta",

    "duel.configuration": "Configuración del Duelo",
    "duel.first_competitor": "Primer competidor",
    "duel.second_competitor": "Segundo competidor",
    "duel.message_to_analyze": "Mensaje a analizar",
    "duel.analysis_language": "Idioma de análisis",
    "duel.launch_duel": "Lanzar Duelo",

    // Concept Section
    "concept.title": "Descubre la imagen que proyectas en línea",
    "concept.intro":
      "Un ciudadano, un consumidor, un banquero, un colaborador o un empleador… Todos tienen un primer réflexe avant de vous faire confiance : taper votre nom ou celui de votre marque sur internet.",
    "concept.questions": "Que vont-ils voir ? Que vont-ils ressentir ? Et surtout, qu'en concluront-ils ?",
    "concept.analysis":
      "C'est exactement ce que nous analysons avec nos outils. Notre outil vous permet de savoir quelle image vous renvoyez lorsqu'on effectue une recherche rapide sur vous ou votre organisation.",
    "concept.measurement":
      "Nous mesurons la présence, la tonalité et la cohérence narrative de vos résultats sur deux canaux décisifs :",
    "concept.seo_channel": "les moteurs de recherche (SEO)",
    "concept.ai_channel": "les IA conversationnelles (GPT et autres)",
    "concept.objective":
      "L'objectif n'est pas de dresser une analyse psychologique ou exhaustive de qui vous êtes réellement, mais de révéler la perception immédiate que les outils numériques construisent autour de votre identité.",
    "concept.summary": "En un mot : ce que les autres voient quand ils vous cherchent.",
    "concept.back_home": "Volver al inicio",
    "concept.hero_title": "Descubre la imagen que proyectas en línea",
    "concept.hero_subtitle":
      "En un mundo digital donde tu reputación se construye con cada búsqueda, comprende cómo te perciben tus clientes, socios y competidores.",
    "concept.first_reflex_title": "El primer reflejo de todos",
    "concept.first_reflex_text":
      "Un ciudadano, un consumidor, un banquero, un colaborador o un competidor. Todos tienen un primer reflejo antes de confiar en ti:",
    "concept.first_reflex_bold": "escribir tu nombre o el de tu marca en internet",
    "concept.what_will_they_see": "¿Qué verán?",
    "concept.what_will_they_see_desc": "Los primeros resultados que aparecen definen tu imagen",
    "concept.what_will_they_feel": "¿Qué sentirán?",
    "concept.what_will_they_feel_desc": "La emoción transmitida por tus contenidos influye en su decisión",
    "concept.what_will_they_conclude": "¿Qué concluirán?",
    "concept.what_will_they_conclude_desc": "Su impresión final determina si confían en ti",
    "concept.analysis_title": "Esto es exactamente lo que analizamos",
    "concept.methodology_tagline": "Una metodología única, un algoritmo robusto",
    "concept.analysis_subtitle":
      "Nuestra tecnología escanea todo tu ecosistema digital para revelarte tu verdadera imagen en línea.",
    "concept.quintilian_quote":
      '« Hoy, cuando buscamos información, ya no nos limitamos a los motores de búsqueda clásicos. También consultamos grandes modelos de inteligencia artificial, que se están convirtiendo en una nueva puerta de entrada al conocimiento. Sin embargo, estas dos fuentes dan visiones diferentes: una refleja lo que realmente existe en línea, la otra refleja lo que se percibe y estructura en su memoria. Quintilian combina ambas para revelar lo que "la web" realmente piensa de ti. El sistema entrega tres puntuaciones claras: presencia, sentimiento y coherencia. »',
    "concept.search_engines": "Motores de búsqueda",
    "concept.seo": "(SEO)",
    "concept.search_engines_desc": "Análisis completo de tu visibilidad en Google, Bing y otros motores de búsqueda",
    "concept.conversational_ai": "IA conversacional",
    "concept.gpt_others": "(GPT y otros)",
    "concept.conversational_ai_desc": "Evaluación de tu reputación con las inteligencias artificiales",
    "concept.cta_button": "Analizar mi reputación ahora",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["fr"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
