"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "fr" | "en" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  fr: {
    // Header
    "header.features": "Fonctionnalités",
    "header.duel": "Mode Duel",
    "header.pricing": "Tarifs",
    "header.contact": "Contact",
    "header.try_free": "Essayez gratuitement",

    // Hero Section
    "hero.title": "Votre réputation en ligne en 3 indicateurs",
    "hero.subtitle":
      "Découvrez en un instant comment Google et l'IA perçoivent votre nom ou votre marque : visibilité, tonalité et cohérence.",
    "hero.name_label": "Nom / Brand",
    "hero.name_placeholder": "Mon identité, mon entreprise, ma marque...",
    "hero.message_label": "Message",
    "hero.message_placeholder": "Vérifiez si cette phrase matche avec votre identité en ligne",
    "hero.language_label": "Langue d'analyse",
    "hero.language_placeholder": "Sélectionnez une langue",
    "hero.analyze_button": "Analyser maintenant",
    "hero.result_time": "Résultat en 60 secondes",
    "hero.secure": "Gratuit et sécurisé",
    "hero.instant_analysis": "Analyse Instantanée",
    "hero.detailed_results": "Résultats détaillés en 60 secondes",

    // Features Section
    "features.title": "3 scores pour comprendre votre impact",
    "features.subtitle": "Une analyse complète de votre présence digitale en quelques secondes",
    "features.presence_title": "Score de présence",
    "features.presence_subtitle": "SEO + visibilité GPT",
    "features.presence_desc": "Voyez si vous existez là où vos clients et les IA vous cherchent.",
    "features.tone_title": "Score de tonalité",
    "features.tone_subtitle": "positif/négatif",
    "features.tone_desc": "Comprenez l'émotion dominante véhiculée par vos contenus.",
    "features.coherence_title": "Score de cohérence narrative",
    "features.coherence_subtitle": "uniformité du message",
    "features.coherence_desc": "Mesure la plausibilité et l'uniformité de votre message.",

    // Use Cases
    "usecases.title": "Pour qui ?",
    "usecases.subtitle": "Un outil adapté à tous les professionnels du digital",
    "usecases.companies": "Entreprises",
    "usecases.companies_desc": "Pilotez votre e-réputation et votre contenu.",
    "usecases.media": "Médias",
    "usecases.media_desc": "Cadrez le ton éditorial multi-plateformes.",
    "usecases.individuals": "Particuliers",
    "usecases.individuals_desc": "Soignez votre présence en ligne.",
    "usecases.agencies": "Agences de communication",
    "usecases.agencies_desc": "Auditez et comparez vos clients en un clin d'œil.",

    // Example Section
    "example.title": "Exemple de résultat",
    "example.subtitle": "Voici à quoi ressemblent vos scores une fois l'analyse terminée",
    "example.presence": "Présence",
    "example.tone": "Tonalité",
    "example.coherence": "Cohérence",
    "example.scale": "Échelle :",
    "example.how_calculated": "Voir comment c'est calculé",

    // Pricing
    "pricing.title": "Tarifs simples et transparents",
    "pricing.subtitle": "Commencez gratuitement, évoluez selon vos besoins",
    "pricing.free_title": "Gratuit",
    "pricing.free_price": "0€",
    "pricing.free_period": "/mois",
    "pricing.free_feature1": "1 analyse par jour",
    "pricing.free_feature2": "Scores de base",
    "pricing.free_feature3": "Historique 7 jours",
    "pricing.free_feature4": "Support communautaire",
    "pricing.free_cta": "Commencer",
    "pricing.pro_title": "Pro",
    "pricing.pro_price": "899€",
    "pricing.pro_period": "/mois",
    "pricing.pro_feature1": "15 analyses par jour",
    "pricing.pro_feature2": "Scores détaillés + insights",
    "pricing.pro_feature3": "Historique illimité",
    "pricing.pro_feature4": "Rapports PDF",
    "pricing.pro_feature5": "Support prioritaire",
    "pricing.pro_feature6": "API access",
    "pricing.pro_cta": "Contacter les ventes",
    "pricing.ultimate_title": "Ultimate",
    "pricing.ultimate_price": "Sur devis",
    "pricing.ultimate_feature1": "Analyses illimitées",
    "pricing.ultimate_feature2": "Scores avancés + IA personnalisée",
    "pricing.ultimate_feature3": "Intégration API complète",
    "pricing.ultimate_feature4": "Rapports personnalisés",
    "pricing.ultimate_feature5": "Support dédié 24/7",
    "pricing.ultimate_feature6": "Formation équipe",
    "pricing.ultimate_feature7": "SLA garanti",
    "pricing.ultimate_cta": "Demander le prix",
    "pricing.popular": "Populaire",

    // Contact
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Une question ? Un besoin spécifique ? Nous sommes là pour vous aider.",
    "contact.form_title": "Envoyez-nous un message",
    "contact.email": "Email",
    "contact.email_placeholder": "votre@email.com",
    "contact.message": "Message",
    "contact.message_placeholder": "Décrivez votre besoin ou votre question...",
    "contact.send": "Envoyer le message",
    "contact.success_title": "Message envoyé !",
    "contact.success_desc": "Nous vous répondrons dans les plus brefs délais.",
    "contact.direct_email": "Ou écrivez-nous directement à",
    "contact.email_required": "L'email est requis",
    "contact.email_invalid": "Format d'email invalide",
    "contact.message_required": "Le message est requis",

    // CTA Section
    "cta.title": "Découvrez votre score en 1 minute",
    "cta.subtitle": "Essayez gratuitement notre analyseur et obtenez vos 3 scores instantanément",
    "cta.button": "Essayer maintenant",

    // Footer
    "footer.description": "L'outil d'analyse de présence digitale qui mesure votre impact en 3 scores.",
    "footer.quick_links": "Liens rapides",
    "footer.features": "Fonctionnalités",
    "footer.pricing": "Tarifs",
    "footer.contact": "Contact",
    "footer.legal": "Légal",
    "footer.legal_mentions": "Mentions légales",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "CGU",
    "footer.contact_title": "Contact",
    "footer.support": "Support disponible 7j/7",
    "footer.copyright": "© 2024 SEO/GPT Score Analyzer. Tous droits réservés.",

    // Info Modal
    "info.title": "Comment sont calculés vos scores ?",
    "info.presence_title": "Score de Présence",
    "info.presence_desc": "Mesure votre visibilité dans les moteurs de recherche et les IA.",
    "info.presence_item1": "Indexation Google",
    "info.presence_item2": "Mentions dans les IA",
    "info.presence_item3": "Autorité du domaine",
    "info.presence_item4": "Backlinks de qualité",
    "info.presence_item5": "Présence réseaux sociaux",
    "info.tone_title": "Score de Tonalité",
    "info.tone_desc": "Analyse l'émotion dominante de vos contenus.",
    "info.tone_item1": "Sentiment positif/négatif",
    "info.tone_item2": "Mots-clés émotionnels",
    "info.tone_item3": "Ton professionnel",
    "info.tone_item4": "Cohérence émotionnelle",
    "info.tone_item5": "Impact sur l'audience",
    "info.coherence_title": "Score de Cohérence",
    "info.coherence_desc": "Évalue l'uniformité de votre message.",
    "info.coherence_item1": "Consistance du message",
    "info.coherence_item2": "Alignement multi-canaux",
    "info.coherence_item3": "Clarté du positionnement",
    "info.coherence_item4": "Crédibilité des informations",
    "info.coherence_item5": "Logique narrative",
    "info.scale_title": "Échelle de notation",
    "info.excellent": "80-100 : Excellent",
    "info.good": "60-79 : Bon",
    "info.improve": "0-59 : À améliorer",

    // Duel
    "duel.title": "Mode Duel",
    "duel.subtitle": "Comparez deux noms ou marques dans le même contexte",
    "duel.name1_placeholder": "Premier nom / marque",
    "duel.name2_placeholder": "Deuxième nom / marque",
    "duel.start_duel": "Commencer le duel",
    "duel.analyzing": "Duel en cours...",
    "duel.results": "Résultats du Duel",
    "duel.winner": "remporte le duel !",
    "duel.global_score": "Score global :",
    "duel.presence": "Présence",
    "duel.sentiment": "Sentiment",
    "duel.coherence": "Cohérence",
    "duel.global": "Score Global",
    "duel.winner_badge": "Vainqueur",
    "duel.comparative_analysis": "Analyse Comparative",
    "duel.vs": "VS",
    "duel.progress": "Progression",

    // Analysis Form
    "analysis.form_title": "Commencez votre analyse",
    "analysis.form_desc": "Remplissez les informations ci-dessous pour analyser votre présence digitale",
    "analysis.name_label": "Nom / Marque à analyser",
    "analysis.name_placeholder": "Mon identité, mon entreprise, ma marque...",
    "analysis.message_label": "Message (optionnel)",
    "analysis.message_placeholder": "Vérifiez si cette phrase matche avec votre identité en ligne",
    "analysis.language_label": "Langue",
    "analysis.language_placeholder": "Sélectionnez une langue",
    "analysis.analyzing": "Analyse en cours...",
    "analysis.analyze_now": "Analyser maintenant",

    // Analysis Modal
    "analysis.title": "Analyse en cours...",
    "analysis.google_search": "Recherche Google",
    "analysis.ai_analysis": "Analyse IA",
    "analysis.calculating": "Calcul des scores",
    "analysis.complete": "Analyse terminée",
    "analysis.results": "Résultats de l'analyse",
    "analysis.google_summary": "Résumé Google",
    "analysis.ai_summary": "Résumé IA",
    "analysis.detailed_analysis": "Analyse Complète",

    // Languages
    "lang.french": "Français",
    "lang.english": "Anglais",
    "lang.spanish": "Espagnol",
    "lang.german": "Allemand",
    "lang.italian": "Italien",
    "lang.portuguese": "Portugais",
    "lang.dutch": "Néerlandais",
    "lang.russian": "Russe",
    "lang.chinese": "Chinois",
    "lang.japanese": "Japonais",
    "lang.arabic": "Arabe",
    "lang.hindi": "Hindi",
    "lang.korean": "Coréen",
    "lang.swedish": "Suédois",
    "lang.norwegian": "Norvégien",
  },
  en: {
    // Header
    "header.features": "Features",
    "header.duel": "Duel Mode",
    "header.pricing": "Pricing",
    "header.contact": "Contact",
    "header.try_free": "Try for Free",

    // Hero Section
    "hero.title": "Your online reputation in 3 indicators",
    "hero.subtitle":
      "Instantly discover how Google and AI perceive your name or brand: visibility, tone, and consistency.",
    "hero.name_label": "Name / Brand",
    "hero.name_placeholder": "My identity, my company, my brand...",
    "hero.message_label": "Message",
    "hero.message_placeholder": "Check if this phrase matches your online identity",
    "hero.language_label": "Analysis language",
    "hero.language_placeholder": "Select a language",
    "hero.analyze_button": "Analyze now",
    "hero.result_time": "Results in 60 seconds",
    "hero.secure": "Free and secure",
    "hero.instant_analysis": "Instant Analysis",
    "hero.detailed_results": "Detailed results in 60 seconds",

    // Features Section
    "features.title": "3 scores to understand your impact",
    "features.subtitle": "Complete analysis of your digital presence in seconds",
    "features.presence_title": "Presence score",
    "features.presence_subtitle": "SEO + GPT visibility",
    "features.presence_desc": "See if you exist where your customers and AIs are looking for you.",
    "features.tone_title": "Tone score",
    "features.tone_subtitle": "positive/negative",
    "features.tone_desc": "Understand the dominant emotion conveyed by your content.",
    "features.coherence_title": "Narrative coherence score",
    "features.coherence_subtitle": "message uniformity",
    "features.coherence_desc": "Measures the plausibility and uniformity of your message.",

    // Use Cases
    "usecases.title": "Who is it for?",
    "usecases.subtitle": "A tool adapted to all digital professionals",
    "usecases.companies": "Companies",
    "usecases.companies_desc": "Manage your e-reputation and content.",
    "usecases.media": "Media",
    "usecases.media_desc": "Frame multi-platform editorial tone.",
    "usecases.individuals": "Individuals",
    "usecases.individuals_desc": "Take care of your online presence.",
    "usecases.agencies": "Communication agencies",
    "usecases.agencies_desc": "Audit and compare your clients at a glance.",

    // Example Section
    "example.title": "Example result",
    "example.subtitle": "Here's what your scores look like once the analysis is complete",
    "example.presence": "Presence",
    "example.tone": "Tone",
    "example.coherence": "Coherence",
    "example.scale": "Scale:",
    "example.how_calculated": "See how it's calculated",

    // Pricing
    "pricing.title": "Simple and transparent pricing",
    "pricing.subtitle": "Start free, scale according to your needs",
    "pricing.free_title": "Free",
    "pricing.free_price": "€0",
    "pricing.free_period": "/month",
    "pricing.free_feature1": "1 analysis per day",
    "pricing.free_feature2": "Basic scores",
    "pricing.free_feature3": "7-day history",
    "pricing.free_feature4": "Community support",
    "pricing.free_cta": "Get Started",
    "pricing.pro_title": "Pro",
    "pricing.pro_price": "€899",
    "pricing.pro_period": "/month",
    "pricing.pro_feature1": "15 analyses per day",
    "pricing.pro_feature2": "Detailed scores + insights",
    "pricing.pro_feature3": "Unlimited history",
    "pricing.pro_feature4": "PDF reports",
    "pricing.pro_feature5": "Priority support",
    "pricing.pro_feature6": "API access",
    "pricing.pro_cta": "Contact sales",
    "pricing.ultimate_title": "Ultimate",
    "pricing.ultimate_price": "Custom quote",
    "pricing.ultimate_feature1": "Unlimited analyses",
    "pricing.ultimate_feature2": "Advanced scores + custom AI",
    "pricing.ultimate_feature3": "Complete API integration",
    "pricing.ultimate_feature4": "Custom reports",
    "pricing.ultimate_feature5": "Dedicated 24/7 support",
    "pricing.ultimate_feature6": "Team training",
    "pricing.ultimate_feature7": "Guaranteed SLA",
    "pricing.ultimate_cta": "Request quote",
    "pricing.popular": "Popular",

    // Contact
    "contact.title": "Contact us",
    "contact.subtitle": "A question? A specific need? We're here to help.",
    "contact.form_title": "Send us a message",
    "contact.email": "Email",
    "contact.email_placeholder": "your@email.com",
    "contact.message": "Message",
    "contact.message_placeholder": "Describe your need or question...",
    "contact.send": "Send message",
    "contact.success_title": "Message sent!",
    "contact.success_desc": "We'll get back to you as soon as possible.",
    "contact.direct_email": "Or write to us directly at",
    "contact.email_required": "Email is required",
    "contact.email_invalid": "Invalid email format",
    "contact.message_required": "Message is required",

    // CTA Section
    "cta.title": "Discover your score in 1 minute",
    "cta.subtitle": "Try our analyzer for free and get your 3 scores instantly",
    "cta.button": "Try now",

    // Footer
    "footer.description": "The digital presence analysis tool that measures your impact in 3 scores.",
    "footer.quick_links": "Quick links",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.legal_mentions": "Legal notices",
    "footer.privacy": "Privacy policy",
    "footer.terms": "Terms of use",
    "footer.contact_title": "Contact",
    "footer.support": "Support available 24/7",
    "footer.copyright": "© 2024 SEO/GPT Score Analyzer. All rights reserved.",

    // Info Modal
    "info.title": "How are your scores calculated?",
    "info.presence_title": "Presence Score",
    "info.presence_desc": "Measures your visibility in search engines and AI.",
    "info.presence_item1": "Google indexing",
    "info.presence_item2": "AI mentions",
    "info.presence_item3": "Domain authority",
    "info.presence_item4": "Quality backlinks",
    "info.presence_item5": "Social media presence",
    "info.tone_title": "Tone Score",
    "info.tone_desc": "Analyzes the dominant emotion of your content.",
    "info.tone_item1": "Positive/negative sentiment",
    "info.tone_item2": "Emotional keywords",
    "info.tone_item3": "Professional tone",
    "info.tone_item4": "Emotional consistency",
    "info.tone_item5": "Audience impact",
    "info.coherence_title": "Coherence Score",
    "info.coherence_desc": "Evaluates the uniformity of your message.",
    "info.coherence_item1": "Message consistency",
    "info.coherence_item2": "Multi-channel alignment",
    "info.coherence_item3": "Positioning clarity",
    "info.coherence_item4": "Information credibility",
    "info.coherence_item5": "Narrative logic",
    "info.scale_title": "Rating scale",
    "info.excellent": "80-100: Excellent",
    "info.good": "60-79: Good",
    "info.improve": "0-59: Needs improvement",

    // Duel
    "duel.title": "Duel Mode",
    "duel.subtitle": "Compare two names or brands in the same context",
    "duel.name1_placeholder": "First name / brand",
    "duel.name2_placeholder": "Second name / brand",
    "duel.start_duel": "Start duel",
    "duel.analyzing": "Duel in progress...",
    "duel.results": "Duel Results",
    "duel.winner": "wins the duel!",
    "duel.global_score": "Global score:",
    "duel.presence": "Presence",
    "duel.sentiment": "Sentiment",
    "duel.coherence": "Coherence",
    "duel.global": "Global Score",
    "duel.winner_badge": "Winner",
    "duel.comparative_analysis": "Comparative Analysis",
    "duel.vs": "VS",
    "duel.progress": "Progress",

    // Analysis Form
    "analysis.form_title": "Start your analysis",
    "analysis.form_desc": "Fill in the information below to analyze your digital presence",
    "analysis.name_label": "Name / Brand to analyze",
    "analysis.name_placeholder": "My identity, my company, my brand...",
    "analysis.message_label": "Message (optional)",
    "analysis.message_placeholder": "Check if this phrase matches your online identity",
    "analysis.language_label": "Language",
    "analysis.language_placeholder": "Select a language",
    "analysis.analyzing": "Analyzing...",
    "analysis.analyze_now": "Analyze now",

    // Analysis Modal
    "analysis.title": "Analysis in progress...",
    "analysis.google_search": "Google Search",
    "analysis.ai_analysis": "AI Analysis",
    "analysis.calculating": "Calculating scores",
    "analysis.complete": "Analysis complete",
    "analysis.results": "Analysis Results",
    "analysis.google_summary": "Google Summary",
    "analysis.ai_summary": "AI Summary",
    "analysis.detailed_analysis": "Complete Analysis",

    // Languages
    "lang.french": "French",
    "lang.english": "English",
    "lang.spanish": "Spanish",
    "lang.german": "German",
    "lang.italian": "Italian",
    "lang.portuguese": "Portuguese",
    "lang.dutch": "Dutch",
    "lang.russian": "Russian",
    "lang.chinese": "Chinese",
    "lang.japanese": "Japanese",
    "lang.arabic": "Arabic",
    "lang.hindi": "Hindi",
    "lang.korean": "Korean",
    "lang.swedish": "Swedish",
    "lang.norwegian": "Norwegian",
  },
  es: {
    // Header
    "header.features": "Características",
    "header.duel": "Modo Duelo",
    "header.pricing": "Precios",
    "header.contact": "Contacto",
    "header.try_free": "Prueba gratis",

    // Hero Section
    "hero.title": "Tu reputación online en 3 indicadores",
    "hero.subtitle":
      "Descubre al instante cómo Google y la IA perciben tu nombre o marca: visibilidad, tono y coherencia.",
    "hero.name_label": "Nombre / Marca",
    "hero.name_placeholder": "Mi identidad, mi empresa, mi marca...",
    "hero.message_label": "Mensaje",
    "hero.message_placeholder": "Verifica si esta frase coincide con tu identidad online",
    "hero.language_label": "Idioma de análisis",
    "hero.language_placeholder": "Selecciona un idioma",
    "hero.analyze_button": "Analizar ahora",
    "hero.result_time": "Resultado en 60 segundos",
    "hero.secure": "Gratis y seguro",
    "hero.instant_analysis": "Análisis Instantáneo",
    "hero.detailed_results": "Resultados detallados en 60 segundos",

    // Features Section
    "features.title": "3 puntuaciones para entender tu impacto",
    "features.subtitle": "Análisis completo de tu presencia digital en segundos",
    "features.presence_title": "Puntuación de presencia",
    "features.presence_subtitle": "SEO + visibilidad GPT",
    "features.presence_desc": "Ve si existes donde tus clientes y las IA te buscan.",
    "features.tone_title": "Puntuación de tono",
    "features.tone_subtitle": "positivo/negativo",
    "features.tone_desc": "Comprende la emoción dominante transmitida por tu contenido.",
    "features.coherence_title": "Puntuación de coherencia narrativa",
    "features.coherence_subtitle": "uniformidad del mensaje",
    "features.coherence_desc": "Mide la plausibilidad y uniformidad de tu mensaje.",

    // Use Cases
    "usecases.title": "¿Para quién?",
    "usecases.subtitle": "Una herramienta adaptada a todos los profesionales digitales",
    "usecases.companies": "Empresas",
    "usecases.companies_desc": "Gestiona tu e-reputación y contenido.",
    "usecases.media": "Medios",
    "usecases.media_desc": "Enmarca el tono editorial multiplataforma.",
    "usecases.individuals": "Particulares",
    "usecases.individuals_desc": "Cuida tu presencia online.",
    "usecases.agencies": "Agencias de comunicación",
    "usecases.agencies_desc": "Audita y compara tus clientes de un vistazo.",

    // Example Section
    "example.title": "Ejemplo de resultado",
    "example.subtitle": "Así es como se ven tus puntuaciones una vez completado el análisis",
    "example.presence": "Presencia",
    "example.tone": "Tono",
    "example.coherence": "Coherencia",
    "example.scale": "Escala:",
    "example.how_calculated": "Ver cómo se calcula",

    // Pricing
    "pricing.title": "Precios simples y transparentes",
    "pricing.subtitle": "Comienza gratis, evoluciona según tus necesidades",
    "pricing.free_title": "Gratis",
    "pricing.free_price": "0€",
    "pricing.free_period": "/mes",
    "pricing.free_feature1": "1 análisis por día",
    "pricing.free_feature2": "Puntuaciones básicas",
    "pricing.free_feature3": "Historial 7 días",
    "pricing.free_feature4": "Soporte comunitario",
    "pricing.free_cta": "Comenzar",
    "pricing.pro_title": "Pro",
    "pricing.pro_price": "899€",
    "pricing.pro_period": "/mes",
    "pricing.pro_feature1": "15 análisis por día",
    "pricing.pro_feature2": "Puntuaciones detalladas + insights",
    "pricing.pro_feature3": "Historial ilimitado",
    "pricing.pro_feature4": "Informes PDF",
    "pricing.pro_feature5": "Soporte prioritario",
    "pricing.pro_feature6": "Acceso API",
    "pricing.pro_cta": "Contactar ventas",
    "pricing.ultimate_title": "Ultimate",
    "pricing.ultimate_price": "Presupuesto personalizado",
    "pricing.ultimate_feature1": "Análisis ilimitados",
    "pricing.ultimate_feature2": "Puntuaciones avanzadas + IA personalizada",
    "pricing.ultimate_feature3": "Integración API completa",
    "pricing.ultimate_feature4": "Informes personalizados",
    "pricing.ultimate_feature5": "Soporte dedicado 24/7",
    "pricing.ultimate_feature6": "Formación del equipo",
    "pricing.ultimate_feature7": "SLA garantizado",
    "pricing.ultimate_cta": "Solicitar precio",
    "pricing.popular": "Popular",

    // Contact
    "contact.title": "Contáctanos",
    "contact.subtitle": "¿Una pregunta? ¿Una necesidad específica? Estamos aquí para ayudarte.",
    "contact.form_title": "Envíanos un mensaje",
    "contact.email": "Email",
    "contact.email_placeholder": "tu@email.com",
    "contact.message": "Mensaje",
    "contact.message_placeholder": "Describe tu necesidad o pregunta...",
    "contact.send": "Enviar mensaje",
    "contact.success_title": "¡Mensaje enviado!",
    "contact.success_desc": "Te responderemos lo antes posible.",
    "contact.direct_email": "O escríbenos directamente a",
    "contact.email_required": "El email es obligatorio",
    "contact.email_invalid": "Formato de email inválido",
    "contact.message_required": "El mensaje es obligatorio",

    // CTA Section
    "cta.title": "Descubre tu puntuación en 1 minuto",
    "cta.subtitle": "Prueba gratis nuestro analizador y obtén tus 3 puntuaciones al instante",
    "cta.button": "Probar ahora",

    // Footer
    "footer.description": "La herramienta de análisis de presencia digital que mide tu impacto en 3 puntuaciones.",
    "footer.quick_links": "Enlaces rápidos",
    "footer.features": "Características",
    "footer.pricing": "Precios",
    "footer.contact": "Contacto",
    "footer.legal": "Legal",
    "footer.legal_mentions": "Avisos legales",
    "footer.privacy": "Política de privacidad",
    "footer.terms": "Términos de uso",
    "footer.contact_title": "Contacto",
    "footer.support": "Soporte disponible 24/7",
    "footer.copyright": "© 2024 SEO/GPT Score Analyzer. Todos los derechos reservados.",

    // Info Modal
    "info.title": "¿Cómo se calculan tus puntuaciones?",
    "info.presence_title": "Puntuación de Presencia",
    "info.presence_desc": "Mide tu visibilidad en motores de búsqueda e IA.",
    "info.presence_item1": "Indexación Google",
    "info.presence_item2": "Menciones en IA",
    "info.presence_item3": "Autoridad del dominio",
    "info.presence_item4": "Backlinks de calidad",
    "info.presence_item5": "Presencia redes sociales",
    "info.tone_title": "Puntuación de Tono",
    "info.tone_desc": "Analiza la emoción dominante de tu contenido.",
    "info.tone_item1": "Sentimiento positivo/negativo",
    "info.tone_item2": "Palabras clave emocionales",
    "info.tone_item3": "Tono profesional",
    "info.tone_item4": "Coherencia emocional",
    "info.tone_item5": "Impacto en la audiencia",
    "info.coherence_title": "Puntuación de Coherencia",
    "info.coherence_desc": "Evalúa la uniformidad de tu mensaje.",
    "info.coherence_item1": "Consistencia del mensaje",
    "info.coherence_item2": "Alineación multicanal",
    "info.coherence_item3": "Claridad del posicionamiento",
    "info.coherence_item4": "Credibilidad de la información",
    "info.coherence_item5": "Lógica narrativa",
    "info.scale_title": "Escala de puntuación",
    "info.excellent": "80-100: Excelente",
    "info.good": "60-79: Bueno",
    "info.improve": "0-59: A mejorar",

    // Duel
    "duel.title": "Modo Duelo",
    "duel.subtitle": "Compara dos nombres o marcas en el mismo contexto",
    "duel.name1_placeholder": "Primer nombre / marca",
    "duel.name2_placeholder": "Segundo nombre / marca",
    "duel.start_duel": "Comenzar duelo",
    "duel.analyzing": "Duelo en curso...",
    "duel.results": "Resultados del Duelo",
    "duel.winner": "¡gana el duelo!",
    "duel.global_score": "Puntuación global:",
    "duel.presence": "Presencia",
    "duel.sentiment": "Sentimiento",
    "duel.coherence": "Coherencia",
    "duel.global": "Puntuación Global",
    "duel.winner_badge": "Ganador",
    "duel.comparative_analysis": "Análisis Comparativo",
    "duel.vs": "VS",
    "duel.progress": "Progreso",

    // Analysis Form
    "analysis.form_title": "Comienza tu análisis",
    "analysis.form_desc": "Completa la información a continuación para analizar tu presencia digital",
    "analysis.name_label": "Nombre / Marca a analizar",
    "analysis.name_placeholder": "Mi identidad, mi empresa, mi marca...",
    "analysis.message_label": "Mensaje (opcional)",
    "analysis.message_placeholder": "Verifica si esta frase coincide con tu identidad online",
    "analysis.language_label": "Idioma",
    "analysis.language_placeholder": "Selecciona un idioma",
    "analysis.analyzing": "Analizando...",
    "analysis.analyze_now": "Analizar ahora",

    // Analysis Modal
    "analysis.title": "Análisis en curso...",
    "analysis.google_search": "Búsqueda Google",
    "analysis.ai_analysis": "Análisis IA",
    "analysis.calculating": "Calculando puntuaciones",
    "analysis.complete": "Análisis completado",
    "analysis.results": "Resultados del Análisis",
    "analysis.google_summary": "Resumen Google",
    "analysis.ai_summary": "Resumen IA",
    "analysis.detailed_analysis": "Análisis Completo",

    // Languages
    "lang.french": "Francés",
    "lang.english": "Inglés",
    "lang.spanish": "Español",
    "lang.german": "Alemán",
    "lang.italian": "Italiano",
    "lang.portuguese": "Portugués",
    "lang.dutch": "Holandés",
    "lang.russian": "Ruso",
    "lang.chinese": "Chino",
    "lang.japanese": "Japonés",
    "lang.arabic": "Árabe",
    "lang.hindi": "Hindi",
    "lang.korean": "Coreano",
    "lang.swedish": "Sueco",
    "lang.norwegian": "Noruego",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["fr"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
